src/lib/actions/analytics.ts
src/routes/console/account/organizations/[[page]]/+page.svelte
src/routes/console/account/organizations/[[page]]/+page.ts
src/routes/console/onboarding/+page.svelte
src/routes/console/organization-[organization]/[[page]]/+page.svelte
src/routes/console/organization-[organization]/[[page]]/+page.ts
src/routes/console/organization-[organization]/settings/+page.svelte
src/routes/console/project-[project]/functions/function-[function]/create.svelte
src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte
src/routes/recover/+page.svelte

fix: QA v16

---

src/routes/recover/+page.svelte

Allows users to set a new password after recovery
https://github.com/appwrite/console/issues/160
Yes

feat: recovery password

---

src/routes/console/project-[project]/auth/settings/+page.svelte

Hides mock Oauth provider from the list
Yes

chore: remove mock oauth

---

src/routes/console/organization-[organization]/header.svelte
src/routes/console/project-[project]/auth/appleOAuth.svelte
src/routes/console/project-[project]/auth/auth0OAuth.svelte
src/routes/console/project-[project]/auth/mainOAuth.svelte
src/routes/console/project-[project]/auth/microsoftOAuth.svelte
src/routes/console/project-[project]/auth/oktaOAuth.svelte

- Fix OAuth path
- Org dropdown closes on click
Yes

fix: QA v17

---

README.md

Removes unwanted PH badge
Visually inspected
No
Yes

remove PH status

---

src/lib/stores/oauth-providers.ts
src/routes/console/project-[project]/auth/authentikOAuth.svelte
src/routes/console/project-[project]/auth/gitlabOAuth.svelte

Add missing OAuth2 components, and links to doc
Manual
https://github.com/appwrite/appwrite/issues/4749
Yes

fix: missing OAuth components, missing links to docs

---

src/routes/console/project-[project]/auth/oktaOAuth.svelte
src/routes/console/project-[project]/overview/keys/[key]/+page@project-[project].svelte
src/routes/console/project-[project]/overview/platforms/[platform]/+page@project-[project].svelte
src/routes/console/project-[project]/overview/platforms/[platform]/android.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/appleIOS.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/appleMacOS.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/appleTvOS.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/appleWatchOS.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/flutterAndroid.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/flutterIOS.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/flutterLinux.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/flutterMacOS.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/flutterWindows.svelte
src/routes/console/project-[project]/overview/platforms/[platform]/web.svelte
src/routes/console/project-[project]/overview/platforms/wizard/android/step1.svelte
src/routes/console/project-[project]/overview/platforms/wizard/apple/step1.svelte
src/routes/console/project-[project]/overview/platforms/wizard/flutter/step1.svelte
src/routes/console/project-[project]/overview/platforms/wizard/store.ts
src/routes/console/project-[project]/overview/platforms/wizard/web/step1.svelte
src/routes/console/project-[project]/settings/webhooks/[webhook]/+page.svelte
src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte

- fixes type issue in storage settings
- pass all arguments with updating resource in storage and projects service
- manually
✅

fix: update projects/storage resources

---

src/lib/actions/analytics.ts

- fix fallback for empty env variables

fix: env fallback

---

src/lib/layout/usage.svelte
src/routes/console/project-[project]/functions/function-[function]/usage/[[period]]/+page.svelte
src/routes/console/project-[project]/functions/function-[function]/usage/[[period]]/+page.ts

Fix: usage stats

---

src/routes/console/account/delete.svelte

Fix account deletion
Manual
https://github.com/appwrite/appwrite/issues/4742
Yes

fix: account deletion

---

src/routes/+layout.ts

- prevents unnecessary account fetching
✅

fix: account fetch waterfall

---

src/lib/components/uploadBox.svelte
src/lib/elements/forms/inputFile.svelte
src/lib/stores/uploader.ts
src/routes/console/project-[project]/auth/user-[user]/updateStatus.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/settings/+page.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/wizard/step2.svelte
src/routes/console/project-[project]/storage/bucket-[bucket]/[[page]]/+page.svelte
src/routes/console/project-[project]/storage/bucket-[bucket]/create.svelte
src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte

- File uploader modal closes on upload, and uploadBox is shown
- Input file style
- Small fixes
Manual
Yes

fix: file upload 

---

src/lib/layout/unauthenticated.svelte
src/routes/+layout.svelte

Allows the user to navigate to the invite page even when logged in.
Manual
https://github.com/appwrite/appwrite/issues/4821
Yes

fix: accept invite while logged in

---

src/routes/console/project-[project]/overview/platforms/wizard/flutter/step1.svelte
src/routes/console/project-[project]/overview/platforms/wizard/web/step1.svelte

Fix wrong gitpod hostname template.
Not nessessary. This is example gitpod workspace url: https://appwrite-appwrite-bi9gcmjr61c.ws-eu77.gitpod.io/
x
Yes

Fix: Gitpod hostname suggestion

---

src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/+page.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/float.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/integer.svelte

Fixes falsy default values on attribute creation not being registered
Manual
- https://github.com/appwrite/appwrite/issues/4712
Yes

Fix: falsy default values not registering on create attribute

---

package-lock.json
package.json
src/lib/stores/project-services.ts

- Add graphql to project services, to allow toggling service status in project settings
**Note:** Requires an updated console SDK to be released first
Existing tests
https://github.com/appwrite/appwrite/pull/974
Yes

Add graphql to project services

---

package-lock.json
package.json
src/routes/console/project-[project]/auth/security/+page.svelte

- User sessions limit for details and review conversation please check
#215 
#215 
YES

feat (auth): user session limit section on auth secutiry

---

src/routes/console/project-[project]/functions/function-[function]/create.svelte

- fixes event on creating deployment
-
- 
✅

fix: create deployment event

---

src/lib/components/permissions/row.svelte

Fixes the copy popover on permission roles
Manual
N/A
Yes

Fix: fixes copy on permission role popover

---

src/lib/elements/table/cellText.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/+page.svelte

Adds brackets on array attributes
Manual
N/A
Yes

Fix: missing brackets on array attributes

---

src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte

- Add settings for the compression algorithm
- Set file size default to MB
Yes

feat: add compression algorithm setting

---

src/lib/elements/forms/inputTags.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/enum.svelte

This PR forces an element to be present when creating an enum attribute
Manual
N/A
Yes

Fix: Attribute enums creatable without elements

---

src/lib/elements/table/cellHead.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/[[page]]/+page.svelte

Changes document tables headings
Manual
N/A
Yes

refactor: remove eyebrow headings in document tables

---

src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/createDocument.svelte

Resets the `createDocument` store correctly
Manual
https://github.com/appwrite/appwrite/issues/4993
Yes :)

fix: create document different collection

---

src/lib/layout/header.svelte

Add logout button to the header dropdown
Manual
Yes

feat: add logout btn to dropdown

---

src/routes/console/project-[project]/overview/platforms/wizard/android/step1.svelte
src/routes/console/project-[project]/overview/platforms/wizard/apple/step1.svelte
src/routes/console/project-[project]/overview/platforms/wizard/flutter/step1.svelte
src/routes/console/project-[project]/overview/platforms/wizard/web/step1.svelte

- adds events for creating platforms
- manual
*n/a*
✅

feat: add events for creating platforms

---

src/routes/console/project-[project]/overview/platforms/+page.svelte

Adds the type to the platforms
Manual 
Yes

feat: add platform type

---

src/routes/console/project-[project]/storage/bucket-[bucket]/file-[file]/+page.svelte

Fixes the deletion text on the File page
Manual
N/A
Yes

Fix: file deletion text

---

src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/indexes/createIndex.svelte

Fix names of subsequent indexes not being incremented correctly
Manual
Yes

fix: incremental indexes name

---

src/routes/console/project-[project]/overview/keys/[key]/+page@project-[project].svelte
src/routes/console/project-[project]/overview/keys/[key]/updateExpirationDate.svelte
src/routes/console/project-[project]/overview/keys/expirationInput.svelte
src/routes/console/project-[project]/overview/keys/wizard/step1.svelte

- Changes predefined dates for Create API Key
- Adds predefined dates for Edit API key
- Fixes expiration date description on Edit API Key
Manual
N/A
Yes

Refactor: API Key forms

---

CONTRIBUTING.md
README.md

Grammar changes suggested by our review agency.
Manual

Grammar changes suggested by review agency.

---

src/lib/actions/analytics.ts

fix: analytics for preview deployments

---

src/lib/actions/analytics.ts
src/lib/helpers/vitals.ts

Changed `console.log` into `console.debug` to make filtering easier
Manual
Yes

chore: change console.log into console.debug to make filtering easier

---

src/lib/elements/forms/inputSelect.svelte
src/lib/helpers/date.ts
src/routes/console/project-[project]/overview/keys/[key]/+page@project-[project].svelte
src/routes/console/project-[project]/overview/keys/[key]/updateExpirationDate.svelte
src/routes/console/project-[project]/overview/keys/expirationInput.svelte
src/routes/console/project-[project]/overview/keys/scopes.svelte
tests/unit/helpers/date.test.ts

Adds small enhancements to the API key page:
- Expiration input will start with a predefined date pre-selected if applicable
- Expiration date alerts when key is expiring/expired
- Helper text for expiration date when using a predefined date option
- Fix the word "scopes" always being in the plural form
Manual
N/A
Yes

Refactor: API key page design details

---

.github/workflows/tests.yml

Changes NPM audit level to low
Manual
N/A
Yes

Chore: change npm audit level to low

---

src/lib/components/feedbackGeneral.svelte

Adds a success alert when feedback is successfully submitted
Manual
N/A
Yes

Feat: add success alert on feedback

---

src/lib/elements/forms/inputCron.svelte

Fixes the issue appwrite#5021. It fixes the validation of cron expression. I figured we could change the regex expression. Because validation issue was coming from client side.
Manual testing in the browser by entering various cron expressions
It fixes the following issue https://github.com/appwrite/appwrite/issues/5021
Yes I have read the contributions guidelines

fix: cron expression regex fix

---

src/lib/components/permissions/row.svelte

Changes the user popover to better reflect the design schema
Manual
N/A
Yes

Fix: user popover spacing

---

tests/unit/setup.ts
vite.config.js

- improve configuration for tests
- remove import mocks
- existing tests
https://github.com/vitest-dev/vitest/issues/2834
✅

test: improve vite config

---

src/lib/elements/forms/index.ts
src/lib/elements/forms/inputCheckbox.svelte
src/lib/elements/forms/inputCron.svelte
src/lib/elements/forms/inputDateTime.svelte
src/lib/elements/forms/inputDomain.svelte
src/lib/elements/forms/inputEmail.svelte
src/lib/elements/forms/inputNumber.svelte
src/lib/elements/forms/inputPassword.svelte
src/lib/elements/forms/inputPhone.svelte
src/lib/elements/forms/inputRadio.svelte
src/lib/elements/forms/inputSecret.svelte
src/lib/elements/forms/inputSelect.svelte
src/lib/elements/forms/inputTags.svelte
src/lib/elements/forms/inputText.svelte
src/lib/elements/forms/inputTextarea.svelte
src/lib/elements/forms/inputURL.svelte
src/lib/elements/forms/label.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributeForm.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/string.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/wizard/step1.svelte

- Creates label component
- Small changes to comply with design schema
Manual
N/A
Yes

refactor: database forms design review

---

src/routes/console/project-[project]/overview/platforms/wizard/apple/step1.svelte
src/routes/console/project-[project]/overview/platforms/wizard/flutter/step1.svelte

Fixes a bug in which the Add Flutter platform wizard doesn't remember platform choice
Manual
N/A
Yes

Fix: Flutter platform wizard persistence

---

src/lib/actions/analytics.ts
src/lib/components/feedbackNPS.svelte
src/lib/constants.ts
src/lib/stores/app.ts
src/lib/stores/sdk.ts
src/lib/system.ts

- assemble all system related informations in one file
- manual
- manual
✅

feat: system service

---

.github/workflows/tests.yml
package-lock.json
package.json
vite.config.ts

- disable audit checks until upgrade svelte kit will work with vitest

tests: disable audit check

---

src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/[[page]]/+page.svelte

Fixes falsy values showing up as n/a
Manual
N/A
Yes

Fix: falsy values showing up as n/a

---

src/routes/console/project-[project]/databases/database-[database]/settings/+page.svelte

Removes avatars from database settings
Manual
N/A
Yes

Fix: remove avatars from database settings

---

CONTRIBUTING.md

Added steps for setting up project for development on local machine including :
1. Cloning repo 
2. Installing dependencies
3. creating .env file from sample.env  
No tests applicable for documentation changes . 
Closes #324
(https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes . I have read the contributing guidelines .

docs: add steps for project development setup

---

src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/createAttribute.svelte

Fixes the issue of states not getting reset in create attribute mentioned in this issue https://github.com/appwrite/appwrite/issues/5133
Manual testing in browser
https://github.com/appwrite/appwrite/issues/5133
Yes

fix states reset issue in create attribute modal

---

CONTRIBUTING.md
src/routes/register/invite/[slug]/+page.svelte

Auto fill the invite code based on the URL

feat: auto fill invite code

---

src/lib/layout/logs.svelte
src/routes/console/project-[project]/auth/user-[user]/memberships/[[page]]/+page.svelte

fix: private executions

---

src/lib/components/drop.svelte
src/lib/components/dropList.svelte
src/lib/components/modal.svelte
src/lib/elements/forms/inputSelectSearch.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/+page.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/relationship.svelte

- Fixes the positioning of the dropdown on InputSelectSearch
- Adds keyboard controls to InputSelectSearch
Manual
- #327 
Yes

feat: proper select search positioning & keyboard controls

---

src/lib/components/permissions/custom.svelte
src/lib/components/permissions/team.svelte
src/lib/components/permissions/user.svelte

Changes some button labels
Manual
N/A
Yes

Refactor: rename buttons

---

src/routes/console/project-[project]/auth/user-[user]/sessions/[[page]]/+page.svelte

Fixs wrong docs link
Manual
N/A
Yes

Fix: wrong docs link

---

src/routes/console/organization-[organization]/header.svelte

- Adds a link on the member avatars on the organization page
Manual
N/A
Yes

feat: clickable member avatars

---

src/routes/console/project-[project]/functions/function-[function]/execute.svelte

fixing a bug
by providing the missing json quotes in the code strings example, the bug was fixed
Tested successfully by rendering the UI with fixed changes
see picture below
Issue Number:  #4940
https://github.com/appwrite/appwrite/issues/4940
(Yes I have read the contributing guidelines .)

Fix 4940 missing properties josn quotes

---

src/lib/components/permissions/roles.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/indexes/createIndex.svelte
src/routes/console/project-[project]/functions/function-[function]/settings/+page.svelte

Fixes button spacing in createIndex modal
Manual
N/A
Yes

fix: x button spacing

---

src/lib/elements/forms/inputId.svelte
src/lib/elements/forms/inputText.svelte
src/lib/elements/forms/inputTextarea.svelte
src/lib/elements/forms/textCounter.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/string.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/string.svelte

- Changes input color based on value
- Use textareas instead of inputs for text inputs with size > 64
Manual
N/A
Yes

Feat: input count dynamic color

---

src/lib/layout/navigation.svelte
src/lib/layout/shell.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/subNavigation.svelte

- Fixes the secondary sidenav having an animation when there's no parent
- Keeps sidenav open when returning from sceondSideNav
Manual
N/A
Yes

fix: limit sidenav transition

---

src/lib/elements/forms/inputSelectSearch.svelte

Conditionally hide clear button on InputSelectSearch
Manual
#327 
Yes

Refactor: input select search hiding x

---

src/lib/components/empty.svelte
src/lib/components/feedbackGeneral.svelte
src/lib/components/feedbackNPS.svelte
src/lib/components/innerModal.svelte
src/lib/components/labelCard.svelte
src/lib/components/permissions/team.svelte
src/lib/components/permissions/user.svelte
src/lib/elements/forms/inputFile.svelte
src/lib/elements/table/cellHead.svelte
src/lib/layout/logs.svelte
src/lib/layout/wizard.svelte
src/routes/console/project-[project]/+error.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/+page.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/+page.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/indexes/+page.svelte
src/routes/console/project-[project]/functions/function-[function]/+page.svelte
src/routes/console/project-[project]/functions/function-[function]/create.svelte
src/routes/console/project-[project]/overview/+layout.svelte
src/routes/console/project-[project]/overview/bandwith.svelte
src/routes/console/project-[project]/overview/platforms/+page.svelte

Add `u-bold` to all `body-text` and remove `u-normal`

reafactor: body text

---

src/routes/console/project-[project]/auth/security/updatePasswordDictionary.svelte
src/routes/console/project-[project]/auth/security/updatePasswordHistory.svelte
src/routes/console/project-[project]/auth/security/updateSessionLength.svelte
src/routes/console/project-[project]/auth/security/updateSessionsLimit.svelte
src/routes/console/project-[project]/auth/security/updateUsersLimit.svelte

Changes user limit text & security cards heading level
Manual
N/A
Yes

refactor: change user limit text & security cards heading level

---

build.js
package-lock.json
package.json

- shows build informations on `npm run build`
- manual
✅

feat: build informations

---

src/lib/elements/forms/inputEmail.svelte
src/lib/elements/forms/inputNumber.svelte
src/lib/elements/forms/inputText.svelte
src/lib/elements/forms/inputTextarea.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/integer.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/string.svelte

fix: inputs nullable

---

src/lib/layout/footer.svelte

- fix cloud icon in footer
- manual
✅

fix: cloud icon

---

src/lib/stores/preferences.ts
src/routes/console/project-[project]/+layout.ts
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/+layout.ts

fix: team prefs

---

src/routes/console/project-[project]/overview/keys/[key]/+page.ts

fixes non-expiring api key disallowing name updates
- Fixes https://github.com/appwrite/appwrite/issues/5370
Yes

fix: non-expiring api key disallowing name updates

---

src/lib/components/empty.svelte
src/lib/components/permissions/team.svelte
src/lib/components/permissions/user.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/+page.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/+page.svelte
src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/indexes/+page.svelte
src/routes/console/project-[project]/functions/function-[function]/executions/+page.svelte
src/routes/console/project-[project]/overview/platforms/+page.svelte

This is a part of our efforts to improve our copy writing. The asana task related can be found here:
https://app.asana.com/0/0/1204427666049041/f

Copy Audit: Remove overly casual language from empty states.

---

src/lib/elements/forms/inputText.svelte
src/lib/elements/forms/inputTextarea.svelte

Removes empty button list from inputs
Manual
Yes
Yes

fix: remove empty button list from inputs

---

src/lib/helpers/copy.ts

Fixes a bug where clinking on a copyable button would cause the page to scroll to the bottom on http pages
Manual
N/A
Yes

fix: copy scrolling to bottom

---

src/routes/console/project-[project]/auth/user-[user]/updateStatus.svelte

Fix a message inversion error
None
None

fix inversed message on (un)verified user

---

CONTRIBUTING.md
src/lib/components/id.svelte

id component copy on click 
Manual
Yes

fix: id component copy on click

---

src/routes/console/project-[project]/functions/function-[function]/header.svelte
src/routes/console/project-[project]/storage/bucket-[bucket]/header.svelte

Changes ID naming in some places e.g. Changes 'Bucket ID' to show actual ID
Manual
N/A
Yes

refactor: change id naming

---

CONTRIBUTING.md
src/routes/console/project-[project]/settings/+page.svelte

When services are "disabled" they are not turned off, they just can't be accessed via client API. This is missing from description 
[(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)
](https://app.asana.com/0/1201596992746623/1203385759000611)
YES

Update description of disabled services.

---

CONTRIBUTING.md
src/routes/console/project-[project]/functions/function-[function]/create.svelte

Fixes https://github.com/appwrite/appwrite/issues/4778
Removes whitespace
Manually test running the command
Yes

Remove trailing space in bash code snippet

---

src/routes/console/project-[project]/auth/gitlabOAuth.svelte

It fixes issue https://github.com/appwrite/appwrite/issues/5421
Tested on console locally
https://github.com/appwrite/appwrite/issues/5421
Yes

fix: issue in gitlab oauth modal validation

---

src/routes/console/project-[project]/overview/platforms/wizard/web/step2.svelte

…ain page
The current link goes to the main npmjs.com page. Maybe this should go to the appwrite package page at https://www.npmjs.com/package/appwrite?

Update link for step 2 in the web platform wizard

---

.github/workflows/tests.yml

The other checks are faster and would result in a faster feedback loop.
Automated CI
None
Yes

Update CI to build last

---

src/routes/console/project-[project]/databases/database-[database]/table.svelte
src/routes/console/project-[project]/databases/table.svelte
src/routes/console/project-[project]/settings/webhooks/+page.svelte

Adds scroll to overflowing tables on mobile
Manuak
Yes

fix: add scroll to tables in mobile

---

src/lib/elements/table/tableScroll.svelte

improves table overflow detection
Manual
N/A
Yes

refactor: improve table overflow detection

---

src/routes/console/project-[project]/functions/function-[function]/settings/updateSchedule.svelte

Update links to new cron docs section in our docs
https://appwrite.io/docs/functions#scheduled-execution

Update link to cron docs

---

src/lib/layout/logs.svelte

Fixes #470 
Checking the links.
#470 
Yes.

Change *Raw Data* links from singular to plural

---

src/routes/console/+layout.svelte

Temporarly disable automatic hackathon redirect
None (tests)
None
Yes

Fix: Disable hackathon redirect

---

src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/+page.svelte

Change to secondary trim utility class

fix: key attribute trim isn't trim

---

src/routes/console/(migration-wizard)/wizard.svelte
src/routes/console/project-[project]/settings/migrations/(import)/step1.svelte
src/routes/console/project-[project]/settings/migrations/(import)/wizard.svelte
src/routes/console/project-[project]/settings/migrations/+page.ts
src/routes/console/project-[project]/settings/migrations/exportModal.svelte

- Added optionals for NHost and Supabase
- Fix Wizard Name
- change migrateAppwrite to createAppwriteMigration
Yes

Small QoL changes

---

src/lib/commandCenter/panels/ai.svelte
src/lib/wizards/functions/components/repositories.svelte
src/lib/wizards/functions/steps/createRepository.svelte
src/routes/console/project-[project]/settings/GitInstallationModal.svelte
src/routes/console/project-[project]/settings/migrations/(import)/step1.svelte
src/routes/console/project-[project]/settings/updateInstallations.svelte

- Set `mode` to `admin`
- Use `project` instead of `projectId` so current project is injected correctly
Manual test

Fix internal calls relying on public scope

---

src/routes/console/project-[project]/functions/function-[function]/settings/updateRuntime.svelte

See https://github.com/appwrite/appwrite/issues/6121
Manual:
* https://github.com/appwrite/appwrite/issues/6121
Yes

Fix the update runtimes dropdown to show available runtimes

---

src/lib/commandCenter/panels/ai.svelte

Fixes AI assistant. admin mode is used for project communication. AI just work even if not inside project.
* https://github.com/appwrite/appwrite/issues/6143
Yes

Fix: AI Assistant

---

src/lib/stores/marketplace.ts

Fixes env var & setup of discord function template
- [x] Manually on QA server
x
Yes

Fix: Discord template

---

src/lib/wizards/functions/cover.svelte

Fix the create function overlay for dark mode
Manual:
* https://github.com/appwrite/appwrite/issues/6264
Yes

Fix the create function overlay for dark mode

---

src/lib/layout/header.svelte
src/lib/pages/domains/wizard/retry.svelte
src/routes/console/+layout.svelte

This will make things consistent with the website and help developers get help faster.
Manual
None
Yes

Update the support links to point to discord

---

package-lock.json
package.json
src/lib/actions/analytics.ts

- in order to gradually move away from Google Analytics, we are adding Plausible to Cloud
- manual https://plausible.io/appwrite.test/
✅

feat: plausible on cloud

---

src/lib/stores/marketplace.ts

Adds support for Dart 3.1 in marketplace of functions
None
x
Yes

Feat:  Dart 3.1 marketplace functions

---

src/routes/console/organization-[organization]/header.svelte

Fixes issue where avatars were being shown in mobile

---

src/lib/layout/footer.svelte

Adds doc link to footer

---

src/lib/stores/marketplace.ts

Add 3.12 version of Python as supported for templates
None
https://github.com/open-runtimes/open-runtimes/pull/211
Y

Feat: Python 3.12

---

src/routes/console/createOrganization.svelte

Added a notice to the create Org dialog 

feat: add notice to create org modal

---

src/lib/wizards/functions/cover.svelte

fix: functions create

---

src/lib/commandCenter/panels/template.svelte
src/routes/+layout.svelte

- fixes color tokens for command center and tooltip
- manual 
✅

fix: color tokens for command center and tooltip

---

src/lib/components/modalSideCol.svelte

fix: two col modal

---

src/routes/console/organization-[organization]/usage/[[invoice]]/+page.ts

No projects in org cause 400 error. It should be empty page instead.
Manual QA
x
Yes

Fix: error page on usage

---

src/routes/console/changeOrganizationTierCloud.svelte
src/routes/console/createOrganizationCloud.svelte
src/routes/console/organization-[organization]/billing/addCreditWizard.svelte
src/routes/console/organization-[organization]/createProjectCloud.svelte

Fixes typo, causing this error
No manual QA, but I compared with other places, and this is how we do it everywhere else.
x
Yes

Fix: missing error message on upgrade on failure

---

src/routes/console/(billing-modal)/hoodieCover.svelte

Adding aspect ratio ensures website doesn't jump (flick) as it loads image
Manual QA
x
Yes

Fix: Image flick

---

src/routes/console/organization-[organization]/+page.svelte
src/routes/console/organization-[organization]/billing/billingAddress.svelte
src/routes/console/organization-[organization]/breadcrumbs.svelte
src/routes/console/organization-[organization]/header.svelte

Fix old region issue

---

src/lib/commandCenter/panels/ai.svelte

Fixes an issue where requests to Appwrite's Assistant would fail

Fix Assistant API error

---

src/lib/components/filters/content.svelte

- update to list in order not to see the bullets + it fixes semantics

Bullet points visible

---

pnpm-lock.yaml
src/routes/console/project-[project]/overview/onboard.svelte

fix: overview media background

---

src/routes/console/project-[project]/auth/user-[user]/sessions/+page.svelte

Fixes the auth user session table overflow in mobile view
Manual
Issue:[ #614 ](https://github.com/appwrite/console/issues/614)
yes

fix: table overflow in mobile view

---

src/lib/constants.ts

Adds `sessions` scope to list of available scopes.
https://github.com/appwrite/appwrite/pull/5777
Yes

feat: ssr - add sessions scope

---

src/lib/components/consent.svelte

fix: responsive consent

---

src/routes/console/organization-[organization]/settings/downloadDPA.svelte

- add missing link to dpa docs
✅

fix: dpa link to docs

---

src/routes/console/changeOrganizationTierCloud.svelte
src/routes/console/createOrganizationCloud.svelte
src/routes/console/organization-[organization]/createProjectCloud.svelte
src/routes/console/organization-[organization]/wizard/step2.svelte

Simplify copy on new billing modals

---

src/lib/constants.ts

chore: rename ssr scopes

---

src/routes/console/project-[project]/messaging/topics/topic-[topic]/subscribers/+page.svelte

Clarify what can be searched.
Manually
Parent:
* https://github.com/appwrite/console/pull/734

Update search subscribers placeholder

---

src/routes/console/project-[project]/messaging/providers/create.svelte
src/routes/console/project-[project]/messaging/providers/store.ts
src/routes/console/project-[project]/messaging/providers/update.svelte
src/routes/console/project-[project]/messaging/providers/wizard/provider.svelte
src/routes/console/project-[project]/messaging/providers/wizard/store.ts

Fix email provider params

---

src/lib/helpers/sizeConvertion.ts
src/lib/helpers/unit.ts
src/routes/console/project-[project]/storage/bucket-[bucket]/settings/updateMaxFileSize.svelte

- Fix incorect size convertion due to base
- FIx incorect unit

Fix-byte-sizes

---

package-lock.json
package.json
src/lib/components/fakeModal.svelte
src/lib/components/modal.svelte
src/lib/components/modalSideCol.svelte

Fix tables not overflowing correctly in modals by adding a wrapper in the Modal componen
:eyes: 
Yes

fix: tables not overflowing in modal

---

src/lib/elements/forms/inputDate.svelte
src/lib/elements/forms/inputTime.svelte
src/routes/console/project-[project]/messaging/wizard/step3.svelte

Adds pointer cursor to date/time fields

---

src/routes/console/project-[project]/storage/bucket-[bucket]/+page.svelte

Updated requested size for file image from 32 to 64

---

src/routes/console/project-[project]/functions/+layout.ts
src/routes/console/project-[project]/functions/function-[function]/settings/+page.ts

- remove duplicate data loadings
- manual
✅

fix: functions race condition for state

---

src/lib/stores/auth-methods.ts

Adds switch for new sign-in method
Manual QA
x
Yes

Feat: Add email OTP toggle

---

package-lock.json
package.json

Chore update sdk

---

src/lib/elements/forms/inputText.svelte
src/routes/console/project-[project]/messaging/providers/store.ts
src/routes/console/project-[project]/messaging/providers/wizard/configure.svelte

Branching from 1.5.x, ensures undefined tooltips are not shown

---

src/routes/console/project-[project]/messaging/providers/store.ts

Fix sendgrid tooltip

---

src/routes/console/project-[project]/messaging/providers/store.ts

Fix tooltip for TextMagic

---

src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateName.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateStatus.svelte

* Fix a bug where some fields like senderEmail were not populating when editing a provider
* Implement update provider name
Manual
None
Yes

Fix editing providers

---

src/routes/console/project-[project]/messaging/createMessageDropdown.svelte
src/routes/console/project-[project]/messaging/message-[message]/+page.svelte
src/routes/console/project-[project]/messaging/message-[message]/pushPreview.svelte
src/routes/console/project-[project]/messaging/wizard/pushFormList.svelte

A bug in the handling of custom data caused an error that prevented the wizard from opening.
Manual
None
Yes

Fix unresponsive edit message

---

src/routes/console/project-[project]/messaging/wizard/pushFormList.svelte

Update custom data tooltip for clarity
Manual:
Previous PR:
* https://github.com/appwrite/console/pull/750
Yes

Update custom data tooltip for clarity

---

src/routes/console/onboarding/+page.svelte

fix: onboarding price

---

src/routes/console/project-[project]/messaging/+page.svelte
src/routes/console/project-[project]/messaging/failedModal.svelte
src/routes/console/project-[project]/messaging/message-[message]/overview.svelte

* Update messages table to show Details link for errors
* Update copy on the message errors modal
* Add a button to view logs in message details
Manual
Parent:
* #808
Yes

Failed message logs

---

src/routes/console/project-[project]/messaging/message-[message]/+page.svelte
src/routes/console/project-[project]/messaging/message-[message]/delete.svelte
src/routes/console/project-[project]/messaging/message-[message]/deleteModal.svelte

Clarify behavior based on status
Manual
None
Yes

Update delete message card and modal

---

src/lib/components/modalWrapper.svelte

fix: hidden modals

---

src/routes/console/project-[project]/messaging/message-[message]/overview.svelte

Show as secondary instead of text to make it stand out more.
Manual:
Previous PR:
* https://github.com/appwrite/console/pull/809
Yes

Update View logs button in message details

---

src/lib/components/empty.svelte

- add padding-top & bottom that focuses on an image will be seen

Empty state card

---

src/routes/console/project-[project]/messaging/topicsModal.svelte

For consistency, it should be:
- Email
- SMS
- Push
Manual:
Email:
SMS:
Push: 
Previous PR:
* https://github.com/appwrite/console/pull/780
Yes

Update message type in select topics modal description

---

src/lib/constants.ts

Remove `accounts.read` and `account.write` scopes

feat: ssr revert scopes

---

src/routes/console/project-[project]/messaging/actions.svelte
src/routes/console/project-[project]/messaging/topicsModal.svelte

Change subscribers > targets for consistency.
Manual:
None
Yes

Update topics modal text

---

package-lock.json
src/lib/elements/forms/inputDate.svelte
src/lib/elements/forms/inputTime.svelte

Updates fields to not show pointer when disabled

---

src/routes/console/project-[project]/settings/migrations/details.svelte

Fixes migration modal, in clean branch

---

src/lib/elements/forms/inputDate.svelte
src/lib/elements/forms/inputTime.svelte

Quick fix for lint error.
CI should pass
None
Yes

Fix lint error

---

src/lib/components/trim.svelte
src/lib/elements/table/cellText.svelte

Fixes tooltip position

---

package-lock.json
package.json
src/routes/console/project-[project]/messaging/providers/create.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateName.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateStatus.svelte
src/routes/console/project-[project]/messaging/providers/store.ts
src/routes/console/project-[project]/messaging/providers/update.svelte
src/routes/console/project-[project]/messaging/providers/wizard/provider.svelte
src/routes/console/project-[project]/messaging/providers/wizard/store.ts
src/routes/login/+page.svelte
src/routes/mfa/+page.svelte
src/routes/register/+page.svelte

Allow setting sandbox to true/false when creating or updating APNS providers

APNS sandbox server support

---

src/routes/console/organization-[organization]/createMember.svelte

Change from title case to sentence case to match our convention and style.
Manual:
None
Yes

Ensure Invite member modal title is sentence cased

---

src/lib/components/clickableListItem.svelte
src/lib/components/collapsibleItem.svelte
src/routes/console/project-[project]/messaging/providers/wizard/configure.svelte

Update "Need a hand?" section based on design feedback
Manual
None
Yes

Update "Need a hand?" section based on design feedback

---

src/routes/console/project-[project]/messaging/providers/provider-[provider]/+page.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateSettings.svelte
src/routes/console/project-[project]/messaging/providers/settingsFormList.svelte
src/routes/console/project-[project]/messaging/providers/store.ts

- update SMTP provider fields based on design review
- fix update SMTP provider updating incorrect param
- fix SMTP provider's Encryption option population for None
Manual
Parent:
* https://github.com/appwrite/console/pull/822
Yes

Fix messaging smtp provider

---

src/lib/stores/project-services.ts

Add messaging to project services

---

src/routes/console/project-[project]/functions/function-[function]/execute.svelte

Update placeholder from json to plain text

Update execution placeholder body

---

src/routes/console/project-[project]/messaging/topics/topic-[topic]/subscribers/+page.svelte

Update link to docs regarding subscribers
Manual
None
Yes

Update link to docs regarding subscribers

---

src/routes/console/project-[project]/messaging/providers/wizard/settings.svelte

* fix docs link
* fix need a hand hover color to match design
Manual
None
Yes

Fix "Need a hand" section in provider settings

---

src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributeItem.svelte

- reduce spacing between rows from 8px to 4px
- reduce the spacing between input from 16px to 8px

Attribute items decrease line spacing

---

src/lib/elements/forms/inputDigits.svelte

Improves UX to auto-submit 6 digit input.
x
Yes

Feat: Add auto-submit logic

---

src/routes/console/project-[project]/messaging/providers/create.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/+page.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateSettings.svelte
src/routes/console/project-[project]/messaging/providers/store.ts
src/routes/console/project-[project]/messaging/providers/wizard/provider.svelte

Telesign changed the params from username and password to customer ID and API key so we need to update the Console to match.
Manual:
Parent:
* TBD
This will also need to be updated:
* https://github.com/appwrite/console/pull/827
Yes

Update telesign params

---

src/lib/actions/analytics.ts
src/routes/console/project-[project]/messaging/topics/topic-[topic]/+page.svelte
src/routes/console/project-[project]/messaging/topics/topic-[topic]/updatePermissions.svelte

Allow developers to update the subscription permissions on a topic.
Manual
None
Yes

Add update subscription permissions card to topic details page

---

src/routes/console/project-[project]/messaging/wizard/step2.svelte

Replace the copy for consistency.
Manual:
None
Yes

Replace subscribers with targets in message wizard

---

src/routes/console/project-[project]/messaging/topicsModal.svelte
src/routes/console/project-[project]/messaging/userTargetsModal.svelte

Also fix spacing in the modals.
* Show count of selected in topics/targets modals
* Fix spacing
Manual
None
None

Show count of selected in topics/targets modals

---

src/lib/commandCenter/commands.ts
src/lib/helpers/omit.ts
src/routes/console/project-[project]/messaging/+layout.svelte

Strips away keys from commands that are overwritten by newer ones
Manual
Of course 😉

Command Center key improvements

---

src/lib/elements/forms/inputDomain.svelte
src/lib/elements/forms/inputEmail.svelte
src/lib/elements/forms/inputFile.svelte
src/lib/elements/forms/inputPassword.svelte
src/lib/elements/forms/inputPhone.svelte
src/lib/elements/forms/inputText.svelte
src/routes/console/project-[project]/messaging/providers/popoverContent.svelte
src/routes/console/project-[project]/messaging/providers/settingsFormList.svelte

fix: popover

---

package-lock.json
src/lib/actions/analytics.ts
src/lib/layout/containerHeader.svelte
src/routes/console/project-[project]/settings/webhooks/+page.svelte
src/routes/console/project-[project]/settings/webhooks/+page.ts
src/routes/console/project-[project]/settings/webhooks/[webhook]/+page.svelte
src/routes/console/project-[project]/settings/webhooks/[webhook]/details.svelte
src/routes/console/project-[project]/settings/webhooks/[webhook]/header.svelte
src/routes/console/project-[project]/settings/webhooks/failedModal.svelte
src/routes/console/project-[project]/settings/webhooks/messageStatusPill.svelte
src/routes/console/project-[project]/settings/webhooks/store.ts

Filter and search will need to wait till it's available in the api

Adds columns to web hooks

---

src/routes/console/project-[project]/messaging/wizard/emailFormList.svelte
src/routes/console/project-[project]/messaging/wizard/pushFormList.svelte
src/routes/console/project-[project]/messaging/wizard/smsFormList.svelte
src/routes/console/project-[project]/messaging/wizard/step2.svelte

Add some validation to the create message wizard so that the user isn't presented with an error on the last step for something wrong on the first step.
Manual
None
Yes

Validate before moving to the next message wizard step

---

src/routes/console/organization-[organization]/createProject.svelte

Disable the create project button to prevent accidental clicks

Disable button

---

package-lock.json
package.json
src/routes/console/account/+layout.ts
src/routes/console/account/deleteMfa.svelte
src/routes/console/account/mfa.svelte
src/routes/console/project-[project]/auth/user-[user]/+layout.ts
src/routes/console/project-[project]/auth/user-[user]/deleteMfa.svelte
src/routes/mfa/+page.svelte

- Applies new changes to SDK after MFA fixes on API
- Adds logout logic in MFA challenge screen
- Accepts recovery codes in challenge flows (login, deleteAuthenticator)
x
Yes

Fix: MFA flows

---

src/routes/console/project-[project]/messaging/providers/wizard/provider.svelte

Don't make the height the same or else there will be extra space.
Manual
None
Yes

Fix provider card height in provider wizard

---

package-lock.json
package.json

chore: update pink

---

src/routes/console/project-[project]/overview/+layout.svelte
src/routes/console/project-[project]/overview/keys/[key]/breadcrumbs.svelte
src/routes/console/project-[project]/overview/platforms/+page.svelte
src/routes/console/project-[project]/settings/updateName.svelte

Sentence case fixes

---

src/lib/components/drop.svelte

fix: dropdowns without arrow

---

src/routes/console/project-[project]/messaging/create.svelte
src/routes/console/project-[project]/messaging/wizard/store.ts

fix: d is null

---

src/lib/stores/oauth-providers.ts
src/routes/console/project-[project]/auth/(providers)/appleOAuth.svelte
src/routes/console/project-[project]/auth/(providers)/auth0OAuth.svelte
src/routes/console/project-[project]/auth/(providers)/authentikOAuth.svelte
src/routes/console/project-[project]/auth/(providers)/gitlabOAuth.svelte
src/routes/console/project-[project]/auth/(providers)/googleOAuth.svelte
src/routes/console/project-[project]/auth/(providers)/mainOAuth.svelte
src/routes/console/project-[project]/auth/(providers)/microsoftOAuth.svelte
src/routes/console/project-[project]/auth/(providers)/oidcOAuth.svelte
src/routes/console/project-[project]/auth/(providers)/oktaOAuth.svelte
src/routes/console/project-[project]/auth/settings/+page.svelte
src/routes/console/project-[project]/functions/function-[function]/+layout.svelte
src/routes/console/project-[project]/functions/function-[function]/execute.svelte
src/routes/console/project-[project]/functions/function-[function]/executions/+page.svelte

- fix oauth modals modals not opening twice
- move oauths into folder
- fix execute modal duplication and opening

fix: modals not opening correctly

---

src/lib/layout/containerHeader.svelte
src/routes/console/project-[project]/storage/bucket-[bucket]/+page.svelte

Fix copy arman

---

src/lib/actions/analytics.ts
src/routes/console/account/deleteMfa.svelte
src/routes/console/project-[project]/auth/user-[user]/deleteMfa.svelte

Fixes: https://github.com/appwrite/appwrite/issues/7778
Manual
https://github.com/appwrite/console/assets/1477010/71275a00-8f60-45bc-9f17-0564f1f666f1
* https://github.com/appwrite/appwrite/issues/7778
Yes

Use project sdk when deleting user authenticator

---

src/routes/console/organization-[organization]/usage/[[invoice]]/+page.svelte

- fix organization execution usage
✅

fix: organization usage execution formatting

---

src/routes/console/project-[project]/messaging/providers/provider-[provider]/+page.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateSettings.svelte

* fix apns sandbox not sending on update
* fix apns sandbox not populating in provider detail
* fix files not fully populating in provier details 
Manual:
https://github.com/appwrite/console/assets/1477010/70be8890-7591-4320-a454-1b9af1c6dddc
None
Yes

Fix APNS update

---

src/routes/console/account/payments/paymentModal.svelte

- fix adding payment method from account page, due to redirect pointing to an org that is not set from the account page yet
✅

fix: add payment from account page

---

src/lib/stores/stripe.ts
src/routes/console/account/payments/+page.svelte
src/routes/console/account/payments/paymentModal.svelte
src/routes/console/organization-[organization]/billing/replaceCard.svelte
src/routes/console/organization-[organization]/billing/retryPaymentModal.svelte
src/routes/console/organization-[organization]/billing/wizard/paymentDetails.svelte
src/routes/console/wizard/cloudOrganizationChangeTier/paymentDetails.svelte

If user is is on an organization page, redirect back to that organization page. Otherwise, redirect back to account page.

fix: confirm payments

---

src/hooks.client.ts
src/routes/+error.svelte
src/routes/console/+error.svelte
src/routes/console/project-[project]/+error.svelte

fix: 500 errors!

---

src/routes/console/wizard/cloudOrganizationChangeTier/paymentDetails.svelte

chore: fix-upgrade-wizard-flow

---

src/routes/console/project-[project]/messaging/providers/store.ts

Remove the period since it's not a sentence.
Manual:
None
Yes

Update SMTP description in provider wizard

---

package-lock.json
package.json
src/routes/console/project-[project]/messaging/providers/create.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/+page.svelte
src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateSettings.svelte
src/routes/console/project-[project]/messaging/providers/store.ts
src/routes/console/project-[project]/messaging/providers/wizard/provider.svelte

In MSG91, the sender number is configured in the template ID and the provider accepts the template ID as a parm instead of a from phone number.
Manual
Server side fix:
* https://github.com/appwrite/appwrite/pull/7824
Related issues:
* https://github.com/appwrite/appwrite/issues/7785
Yes

Replace MSG91 sender number with template ID

---

package-lock.json
package.json
src/lib/stores/billing.ts
src/lib/stores/stripe.ts
src/lib/wizards/functions/components/repositories.svelte
src/routes/+layout.svelte
src/routes/+layout.ts
src/routes/console/+error.svelte
src/routes/console/+layout.svelte
src/routes/console/account/payments/+page.svelte
src/routes/console/account/payments/paymentModal.svelte
src/routes/console/organization-[organization]/billing/replaceCard.svelte
src/routes/console/organization-[organization]/billing/retryPaymentModal.svelte
src/routes/console/organization-[organization]/billing/wizard/paymentDetails.svelte
src/routes/console/project-[project]/overview/platforms/createAndroid.svelte
src/routes/console/project-[project]/overview/platforms/createApple.svelte
src/routes/console/project-[project]/overview/platforms/createFlutter.svelte
src/routes/console/project-[project]/overview/platforms/createWeb.svelte
src/routes/console/wizard/cloudOrganizationChangeTier/paymentDetails.svelte

Routine sync between main and cloud branches

chore: sync main and cloud

---

src/routes/console/organization-[organization]/billing/replaceCard.svelte

Fix:
Stripe form not loading
Card not being selected when the existing payment method belongs to another user

fix: replace card flow

---

src/lib/sdk/billing.ts
src/routes/console/organization-[organization]/billing/availableCredit.svelte

Fixing type to calculate the total correctly
Backend fix:
https://github.com/appwrite-labs/cloud/pull/623

refactor: credits type

---

src/routes/console/account/sessions/+page.svelte
src/routes/console/project-[project]/auth/user-[user]/sessions/+page.svelte

Set the size so the image and icon have the correct size.
Manual
Account
User
Previous PR:
* https://github.com/appwrite/console/pull/436

Fix session avatar image and icon sizes

---

src/routes/console/account/updateMfa.svelte

fix: mfa link

---

src/lib/actions/analytics.ts
src/lib/constants.ts
src/routes/console/project-[project]/auth/user-[user]/header.svelte
src/routes/console/project-[project]/auth/user-[user]/identities/+page.svelte
src/routes/console/project-[project]/auth/user-[user]/identities/+page.ts
src/routes/console/project-[project]/auth/user-[user]/identities/table.svelte

Show users' identities and allow deleting them.
Manual
Child:
* https://github.com/appwrite/console/pull/921
Yes

Add tab to show user's identities

---

src/routes/console/organization-[organization]/settings/+page.svelte
src/routes/console/organization-[organization]/settings/deleteOrganizationModal.svelte

Show organization deletion modal on self hosted instances.
Manual.
https://github.com/appwrite/console/assets/20625965/a2e38714-2085-47b5-a2ec-0fc70e3ecb30
* #1030
Yes.

Fix: Show Delete Org. Modal on Self Hosted Instances

---

src/lib/stores/marketplace.ts

Add LMNT Demo

---

src/lib/stores/marketplace.ts

Add Together AI Demo to console
Yes

Feat Together AI

---

src/routes/console/project-[project]/messaging/providers/provider-[provider]/updateSettings.svelte

The link to the docs were incorrect. This PR updates the link.
Fixes #972 
Manual
* #972 
Yes

Fix messaging provider link in settings

---

src/lib/components/alert.svelte

Update style x button size of Alert partial to vertically align the alert icon on the left w/ the x icon on the right.

Update style x button size of Alert partial (reviewed with Chen)

---

src/lib/wizards/functions/steps/createRepository.svelte

Inputs are list elements (li) so they must be wrapped with a form list (ul) to prevent the bullet point from showing.
Before
After
None
Yes

Wrap input with form list so bullet point doesn't show

---

src/routes/console/organization-[organization]/+layout.ts
src/routes/console/organization-[organization]/settings/deleteOrganizationModal.svelte

Fixes https://github.com/appwrite/appwrite/issues/7736, https://github.com/appwrite/console/issues/1030
Deleting an org with another org:
https://github.com/appwrite/console/assets/1477010/baf46c82-5993-4d38-9b4a-df36db257c06
Deleting an org without any other orgs:
https://github.com/appwrite/console/assets/1477010/0261fbb0-8718-46ab-afb0-b4ba7f70951d
* https://github.com/appwrite/appwrite/issues/7736
* https://github.com/appwrite/console/issues/1030

Fix redirect after deleting org

---

package-lock.json
package.json

Update pink to [pink](https://github.com/appwrite/pink/releases/tag/%40appwrite.io%2Fpink%400.19.0) and [pink-icons](https://github.com/appwrite/pink/releases/tag/%40appwrite.io%2Fpink-icons%400.19.0) to 0.19.0. Changes include:
* https://github.com/appwrite/pink/pull/139
* https://github.com/appwrite/pink/pull/162
* https://github.com/appwrite/pink/pull/178
* https://github.com/appwrite/pink/pull/171
* https://github.com/appwrite/pink/pull/179
* https://github.com/appwrite/pink/pull/181
* https://github.com/appwrite/pink/pull/182
* https://github.com/appwrite/pink/pull/183
* https://github.com/appwrite/pink/pull/184
* https://github.com/appwrite/pink/pull/172
* https://github.com/appwrite/pink/pull/185
* https://github.com/appwrite/pink/pull/186
* …

Bump pink and pink-icons versions

---

.github/workflows/e2e.yml

- sec context for CI target brach 
✅

fix: ci context for e2e tests

---

src/lib/layout/header.svelte

- Update header tag content height
- Replaced inline style of padding with utility class

Update header tag content height (of BETA tag text) 

---

src/routes/console/account/updateMfa.svelte

Add verified pill to clarify the method is there because the email is verified.
Manual:
None
Yes

feat(auth): add verified pill to mfa methods

---

.github/workflows/e2e.yml
tests/e2e/journeys/upgrade-free-tier.spec.ts
tests/e2e/steps/pro-project.ts

tests: fix flaky locator

---

.npmrc

Revert "test"

---

src/routes/console/project-[project]/functions/function-[function]/deploymentSource.svelte

Adds the CLI as an option for function deployment type

feat: Adding cli as a function deployment type

---

src/lib/stores/migration.ts

This fixes the database option in the migration wizard to migrate databases, collections, attributes and indexes if the database option is selected.
Yes

Fix Database Option in Migrations

---

src/lib/components/cardGrid.svelte

Fixed the missing padding on the mobile for the danger card. (issue: https://github.com/appwrite/console/issues/1086)

Fixed padding for left side on mobile for danger card

---

src/lib/components/cardContainer.svelte
src/lib/layout/footer.svelte

- bucket increase size
- Footer break for two rows if needed

Mobile style fixes

---

src/routes/console/project-[project]/functions/function-[function]/deployment-[deployment]/+page.svelte

Fixes realtime logs for functions.
Manaul.
- https://github.com/appwrite/appwrite/issues/6237
Yes.

Fix Functions Realtime Logs

---

src/lib/pages/domains/wizard/step1.svelte

Fixes #1040
Verified with the error notification shown and wizard doesn't proceed to next step.
Yes

Fix: throw an error if invalid domain is added to a function

---

src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte

Fixes #931 
Verified that the file extension list scrolls on both desktop and mobile.
Yes

Added scroll class to listItem containing the extension pills

---

src/routes/console/organization-[organization]/wizard/step1.svelte
src/routes/console/organization-[organization]/wizard/step2.svelte
src/routes/console/organization-[organization]/wizard/store.ts

- load regions before showing the selection
✅

fix: load regions

---

src/lib/layout/progress.svelte
src/routes/console/project-[project]/+page.ts

- prevent multiple navigation events to reset the progress bar
- adds a threshold to prevent showing the bar in under 150ms
✅

fix: progress bar

---

src/routes/console/apply-credit/+page.svelte

fix: remove  undefined variable

---

src/lib/elements/forms/inputTime.svelte
src/routes/console/project-[project]/functions/function-[function]/executions/execute-function/+page.svelte

We can now set a custom step for time inputs

feat: time input custom step

---

src/routes/console/organization-[organization]/billing/paymentHistory.svelte
src/routes/console/organization-[organization]/billing/planSummary.svelte

- filter invoices by `billingCurrentInvoiceDate`
✅

fix: invoice pagination

---

src/lib/layout/header.svelte
src/routes/console/organization-[organization]/header.svelte

- in case you are already loaded an organization, the preload will mess with the state - this is a hotfix for this
✅

fix: preloading mismatch

---

src/routes/console/organization-[organization]/change-plan/+page.svelte
src/routes/console/organization-[organization]/header.svelte

- redirect was missing after downgrading an org
✅

fix: downgrade redirect

---

src/lib/sdk/functionsSpec.ts
src/lib/stores/sdk.ts
src/routes/console/project-[project]/functions/+layout.ts
src/routes/console/project-[project]/functions/function-[function]/settings/updateRuntime.svelte
src/routes/console/project-[project]/functions/function-[function]/store.ts
src/routes/console/project-[project]/functions/store.ts

This PR introduces the controls for Memory and CPU on function runtimes and is tied to https://github.com/appwrite/appwrite/pull/8251
* https://github.com/appwrite/appwrite/pull/8251
Yes

Add runtime memory and CPU Controls

---

.github/workflows/e2e.yml
.github/workflows/tests.yml
playwright.config.ts
tests/e2e/steps/pro-project.ts

- hardcode public stripe key for testing
- add timeout to make e2e less flaky
- ci
✅

ci: harden e2e

---

src/routes/console/organization-[organization]/wizard/step2.svelte

Update copy as per designs in [Figma](https://www.figma.com/design/LTuiex3LVEiQ68VMpI3hN6/Billing-G2?node-id=3721-19476&t=WWwvm12VN7GQYmdA-1)

Update region notification copy

---

playwright.config.ts

ci: add retries and tracing to e2e tests

---

src/lib/stores/app.ts
src/routes/(console)/project-[project]/auth/settings/+page.svelte
src/routes/(console)/project-[project]/auth/user-[user]/identities/table.svelte
src/routes/(console)/project-[project]/overview/onboard.svelte

fix: icon paths

---

tests/e2e/steps/pro-project.ts

- wait for modal to close before submitting form
✅

test: improve stability of e2e tests

---

Dockerfile
src/lib/components/empty.svelte
src/lib/components/emptyFilter.svelte
src/lib/components/emptySearch.svelte

fix: image heights to prevent cls

---

src/routes/console/(migration-wizard)/resource-form.svelte

This fixes a couple of small issues within the migrations wizard, including the functions warning showing up on non-appwrite platforms and the automatic use of subdomain for the domain not working for the reports.
Yes

Small Migrations Fixes

---

src/lib/components/support.svelte
src/routes/console/supportWizard.svelte
src/routes/console/wizard/support/store.ts

Update the support window to match the time where the Success team is available.
Support button/dropdwon
Support Wizard:
None
Yes

Update support window

---

src/lib/components/secondaryTabsItem.svelte
tests/unit/components/dropTabsItem.test.ts
tests/unit/components/tab.test.ts

tests: fix tab selectors

---

src/routes/console/project-[project]/auth/user-[user]/updatePrefs.svelte

- Fix bug where the removal of the first pref would remove them all
- Fix all prefs can now be removes and the "Update" button is clickable

fix: user preferences removal bug

---

package.json
src/lib/components/eyebrowHeading.svelte
src/lib/components/secondaryTabs.svelte
src/lib/elements/flag.svelte
src/lib/elements/forms/button.svelte
src/lib/elements/table/cellButton.svelte
src/lib/elements/table/cellCheck.svelte
src/lib/elements/table/index.ts
src/lib/elements/table/tableScroll.svelte
src/lib/layout/navigation.svelte
src/lib/layout/shell.svelte

fix: subnav with scrolling sticky table

---

package-lock.json
package.json
src/lib/elements/forms/inputSelect.svelte
src/routes/console/project-[project]/functions/+layout.ts
src/routes/console/project-[project]/functions/function-[function]/settings/updateRuntime.svelte
src/routes/console/project-[project]/functions/function-[function]/usage/[[period]]/+page.svelte
src/routes/console/project-[project]/functions/store.ts

Reverts appwrite/console#1247 because the backend has not been so these API calls will return 404.
Fixes https://github.com/appwrite/appwrite/issues/8510
Screenshot of function page loading:

Revert "Feat implement runtime controls"

---

src/routes/console/project-[project]/auth/security/updateUsersLimit.svelte

Fixes the label alignment.
Manual.
N/A.
Yes.

Fix Input Label Alignment

---

src/routes/(console)/project-[project]/functions/function-[function]/executions/+page.svelte

Remove Icon Plus

---

src/lib/components/emptyCardImageCloud.svelte
src/lib/elements/forms/helper.svelte
src/routes/(console)/project-[project]/auth/security/updateMockNumbers.svelte

fix: address review comments

---

src/lib/elements/forms/helper.svelte
src/lib/elements/forms/inputPhone.svelte

Use different CSS selectors so they are not removed during build

chore: review commetns

---

src/lib/wizards/functions/createTemplate.svelte
src/lib/wizards/functions/steps/templateDeployment.svelte
src/lib/wizards/functions/steps/templatePermissions.svelte

- Improves copy in deployment screen of function template creation
- Ensures empty scopes looks good, and doesn't skip the step
---
x
Yes

Feat: Improve template flow

---

src/routes/(console)/project-[project]/functions/function-[function]/deployment-[deployment]/+page.svelte
src/routes/(console)/project-[project]/functions/function-[function]/table.svelte

Allows deployment download at any step of deployment
https://github.com/user-attachments/assets/b8f92f35-2561-465e-97ad-52565cba43cf
x
Yes

Fix: Deployment download button

---

package.json
pnpm-lock.yaml
src/routes/(console)/account/mfa.svelte
src/routes/(console)/project-[project]/functions/function-[function]/+page.svelte
src/routes/(console)/project-[project]/functions/function-[function]/deploymentCard.svelte
src/routes/(console)/project-[project]/functions/function-[function]/executions/execute-function/+page.svelte
src/routes/(console)/project-[project]/functions/function-[function]/table.svelte

- Support for separate build&deployment sizes
https://github.com/user-attachments/assets/a7e6519c-36ce-415e-b34f-479893c878fa
x
Yes

Separate build and deployment sizes

---

package.json
pnpm-lock.yaml

fix-upgrade-go-version

---

package-lock.json
src/routes/(console)/project-[project]/auth/security/updateMockNumbers.svelte

chore: update mock numbers

---

package.json
pnpm-lock.yaml

chore: bump console sdk

---

src/routes/(console)/project-[project]/storage/bucket-[bucket]/+page.ts

fix: storage waterfall

---

.github/workflows/publish.yml

ci: fix missing sentry var for cloud build

---

src/routes/(console)/organization-[organization]/settings/downloadDPA.svelte

Fix: Correct DPA Download Url

---

src/routes/(console)/project-[project]/auth/security/updateMockNumbers.svelte

Fix: Correct Upgrade Url

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/edit.svelte

fix: edit attribute state

---

src/routes/(console)/project-[project]/functions/function-[function]/executions/execute-function/+page.svelte

fix: function execute wizard

---

src/routes/(console)/project-[project]/storage/bucket-[bucket]/+page.svelte

1. Remove Update button because it doesn't do anything
2. Fix spacing in the first column because the file name was unaligned
Before:
After:
None
Yes

Update how pending uploads look

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/+page.svelte

Change edit attribute -> update attribute

---

src/lib/stores/uploader.ts
src/routes/(console)/project-[project]/storage/bucket-[bucket]/+page.svelte

Revert "Fix: Upload Context Switches"

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/boolean.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/datetime.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/edit.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/email.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/enum.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/float.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/integer.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/ip.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/url.svelte

- fix always using the original key when updating attributes
- manually tested every attribute type
✅

fix: update attributes

---

docker/nginx.conf

- on systems that don't support ipv6, this does ipv4 by default
✅

fix: nginx conf compatibility with ipv4/v6

---

src/lib/constants.ts
src/routes/(console)/organization-[organization]/+layout.ts
src/routes/(console)/project-[project]/+layout.ts

default scopes for self-hosted

---

src/routes/console/organization-[organization]/createMember.svelte

feat: console roles 

---

src/lib/components/roles/default.svelte
src/lib/components/roles/roles.svelte
src/lib/components/roles/upgrade.svelte
src/routes/(console)/organization-[organization]/createMember.svelte
src/routes/(console)/project-[project]/bottomAlerts.ts

fix: link to role docs

---

src/lib/components/bottomModalAlert.svelte
src/lib/stores/bottom-alerts.ts
src/routes/(console)/+layout.svelte
src/routes/(console)/bottomAlerts.ts
src/routes/(console)/organization-[organization]/createMember.svelte
src/routes/(console)/project-[project]/+layout.svelte

Scopes to Bottom Alerts

---

src/lib/components/bottomModalAlert.svelte

Fix: Modal Visibility on Mobile

---

src/lib/stores/campaigns.ts

Minor typo fix in Hacktoberfest campaign copy
#1361 
Yes

Fix typo in Hacktoberfest campaign

---

src/lib/elements/forms/inputCheckbox.svelte
src/routes/+layout.svelte

Correct color for unchecked checkboxes on dark theme

---

src/lib/components/bottomModalAlert.svelte

Modal Expiration

---

src/lib/components/collapsibleItem.svelte
src/lib/components/creditCardInfo.svelte
src/routes/(console)/account/payments/paymentMethods.svelte

Various padding fixes

---

src/routes/(console)/project-[project]/settings/smtp/+page.svelte

Fixes https://github.com/appwrite/appwrite/issues/8438
Manually in the console 

fix: getting value instead of specific enum value

---

src/lib/wizards/functions/cover.svelte
src/routes/(console)/project-[project]/functions/templates/+page.svelte
src/routes/(console)/project-[project]/functions/templates/+page.ts

Fixes https://github.com/appwrite/console/issues/1391
* https://github.com/appwrite/console/issues/1391

Fix case sensitive search

---

src/routes/(console)/project-[project]/settings/webhooks/createWebhook.svelte

Fix webhook exit copy

---

src/lib/components/eventModal.svelte
src/lib/components/permissions/label.svelte
src/lib/helpers/date.ts
src/lib/sdk/billing.ts
src/lib/stores/headerAlert.ts
src/lib/stores/stripe.ts
src/routes/(console)/(migration-wizard)/resource-form.svelte
src/routes/(console)/project-[project]/auth/user-[user]/updateStatus.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/enum.svelte
src/routes/(console)/project-[project]/functions/function-[function]/settings/updateConfiguration.svelte
src/routes/(console)/project-[project]/messaging/smsPhone.svelte
src/routes/(console)/project-[project]/messaging/wizard/step3.svelte
src/routes/(console)/project-[project]/overview/+layout.svelte
src/routes/(console)/project-[project]/overview/bandwidth.svelte
src/routes/(console)/project-[project]/settings/transferProject.svelte
src/routes/(public)/card/Card.svelte

Hello appwrite team. This PR fixes numerous typos that were spotted in
- comments
- in-app strings
- function/variable namings
- CSS namings
- Bandwidth component naming
The typos were found via the [crate-ci/typos](https://github.com/crate-ci/typos) CLI.
The file `sizeConvertion.ts` has a typo in it where it should be `conversion`. However, I did not fix that as the file is being referenced in a lot of other files which will increase the diffs in this PR. Do let me know if I can help to address that too, thanks!
As long as the existing test passes, this PR will not break anything.
I have read through the CONTRIBUTING.md and noticed that an issue is needed for a pull request, let me know if this is also required for this PR so I can create an issue for it. Thanks!
I have read through …

Refactor fix typos

---

src/lib/components/bottomModalAlert.svelte

Hide all promo alerts on cancel

---

src/routes/(console)/organization-[organization]/+layout.ts
src/routes/(console)/project-[project]/+layout.ts

fix: selfhosted roles

---

src/lib/components/billing/planSelection.svelte
src/lib/constants.ts
src/lib/sdk/billing.ts
src/lib/stores/billing.ts
src/routes/(console)/organization-[organization]/billing/planSummary.svelte
src/routes/(console)/organization-[organization]/change-plan/+page.svelte

Feat pro 1313 support custom plan

---

package.json
pnpm-lock.yaml

Fixes runtime enum issues in last SDK release
x
yes

Chores: Update sdk dependency

---

src/routes/(console)/organization-[organization]/billing/planSummary.svelte

Fix nullpointer on addon member price

---

src/lib/components/backupDatabaseAlert.svelte
src/routes/(console)/project-[project]/databases/database-[database]/backups/createPolicy.svelte

Fix: Button type to avoid unintended submission trigger

---

src/routes/(console)/project-[project]/settings/migrations/+page.ts

Excludes the backup and restorations from migrations list under project settings in the migrations tab.

Update query for migrations

---

src/lib/components/backupDatabaseAlert.svelte
src/lib/layout/containerHeader.svelte
src/routes/(console)/project-[project]/databases/database-[database]/backups/createPolicy.svelte

Update copy for custom retention

---

src/routes/(console)/organization-[organization]/usage/[[invoice]]/+page.svelte
src/routes/(console)/project-[project]/settings/usage/[[invoice]]/+page.svelte

fix: storage pricing copy

---

src/lib/components/backupRestoreBox.svelte

fix: backup progress

---

src/routes/(console)/project-[project]/databases/create.svelte

fix: duplicate id on creating multiple databases with policy

---

src/routes/(console)/project-[project]/updateVariables.svelte

Fix overflow variablecard when just slightly bigger than mobile

---

src/lib/elements/forms/inputId.svelte
tests/unit/elements/inputId.test.ts

Align the regex and explanation text for custom project ID's with the server requirements.
✅

Change regex for custom project id

---

src/routes/(console)/organization-[organization]/wizard/step2.svelte

Fix active regions to show first

---

src/lib/helpers/backups.ts
src/routes/(console)/project-[project]/databases/database-[database]/backups/store.ts

Set default pro plan policy schedule to midnight local time

---

src/routes/(console)/bottomAlerts.ts

Remove the promo for new roles feature
✅

Remove the promo card for roles

---

src/lib/sdk/billing.ts

Method [should be patch](https://github.com/appwrite-labs/cloud/blob/22dc7a831aaacc0ea7bdf330f0566040387bbc1b/app/controllers/api/account.php#L219)

Fix payment method setup route type

---

playwright.config.ts
src/routes/(console)/organization-[organization]/billing/paymentHistory.svelte
src/routes/(console)/organization-[organization]/change-plan/+page.svelte
src/routes/(console)/organization-[organization]/settings/deleteOrganizationModal.svelte
tests/e2e/journeys/upgrade-free-tier.spec.ts

- don't show pending invoices
- fix redirects
- alter succes message
✅

Fix billing issues

---

src/routes/(console)/organization-[organization]/billing/planSummary.svelte

(slowed down for demo purposes)
Before:
https://github.com/user-attachments/assets/698d259c-d4fc-4663-9865-9420b32c3520
After:
https://github.com/user-attachments/assets/d8dd31db-bc8f-4a93-95c1-dcd2083cc215
✅

Better fallback values

---

src/routes/(console)/project-[project]/settings/migrations/+page.ts

Fix migrations query

---

src/lib/elements/forms/inputId.svelte
src/routes/(console)/organization-[organization]/wizard/step1.svelte
src/routes/(console)/project-[project]/databases/database-[database]/createCollection.svelte
tests/unit/elements/inputId.test.ts

Fix the too tight custom id regex implementation
✅

Fix input id regex

---

src/lib/helpers/notifications.ts

Update syntax to prevent prefs nullpointer
✅

Improve prefs nullpointer fix

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/createAttribute.svelte

Removes the feedback notification after creating multiple attributes
✅

Fix cleanup feedback attribute notification

---

playwright.config.ts

Fix testing endpoint

---

src/routes/+page.ts

Correctly handle loading the GitHub Education program when the user is already signed into console
✅

Fix allow GitHub education when signed in

---

src/routes/(console)/project-[project]/functions/templates/+page.svelte

Fix: Broken `deno` logo on templates filter

---

src/routes/(console)/organization-[organization]/billing/+page.svelte
src/routes/(console)/organization-[organization]/billing/+page.ts
src/routes/(console)/organization-[organization]/billing/planSummary.svelte

Pre-load all plan summary data in +page.ts
✅

Load all data for plan summary in advance

---

src/lib/helpers/notifications.ts

- fallback check to account for an empty array being returned was not accessiing possible null values correctly
- manual
✅

fix: prefs empty array case

---

src/themes/dark-cloud.json
src/themes/dark.json
src/themes/light-cloud.json
src/themes/light.json

Fix Skeleton overlay color

---

src/lib/components/backupRestoreBox.svelte
src/lib/components/consent.svelte
src/lib/components/migrationBox.svelte
src/lib/components/modalSideCol.svelte
src/lib/components/modalWrapper.svelte
src/lib/elements/forms/inputDigits.svelte
src/lib/layout/unauthenticated.svelte
src/routes/(authenticated)/mfa/+page.svelte
src/routes/(console)/account/updateMfa.svelte
src/routes/(console)/project-[project]/+layout.svelte
src/routes/(console)/project-[project]/functions/function-[function]/deploymentCard.svelte
src/routes/(console)/project-[project]/overview/onboard.svelte
src/routes/(public)/auth/oauth2/failure/+page.svelte
src/routes/(public)/auth/oauth2/success/+page.svelte
src/routes/+layout.svelte

- remove initial fetches for migrations and restorations
- rely on realtime for that
- fix scss build warnings
✅

fix: unnecessary fetches and build warnings

---

src/routes/(console)/organization-[organization]/settings/BAAModal.svelte
src/routes/(console)/organization-[organization]/settings/Soc2Modal.svelte

Update the subject and message to be more description.
Ensure website is also passed along in the request.
Manually tested locally.
None
Yes

Update BAA and SOC-2 request modals

---

src/routes/(console)/organization-[organization]/header.svelte

fix: pill centering with eyebrow heading

---

src/routes/(console)/organization-[organization]/billing/availableCredit.svelte

Make it visually more clear what credits are expired.
✅

Add more clarity into expired credits

---

src/routes/(console)/organization-[organization]/billing/planSummary.svelte

Remove sentence

---

src/routes/(console)/bottomAlerts.ts

Don't show the banner for the new backups features when on self hosted
✅

Only add backups notification on cloud

---

src/routes/(console)/organization-[organization]/billing/planSummary.svelte

Fix for nullpointer when no invoices are yet available
✅

Fix for when no invoices are available

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/indexes/createIndex.svelte

Fix notification on index creation error

---

src/lib/components/paginationWithLimit.svelte

Fix pagination alignment

---

src/lib/components/migrationBox.svelte
src/routes/(console)/project-[project]/settings/migrations/+page.svelte

Fix migration progress bar

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/table.svelte

Fix Table Content Truncated

---

src/routes/(console)/project-[project]/databases/table.svelte

Removes checkboxes and bulk deletion from Databases table to create friction so that a user doesn't mistakenly delete any important data.
Manual.
N/A.
Yes.

Remove bulk deletions on database table

---

src/lib/constants.ts

Fixes const for scopes, using wrong names
None

Fix: site scopes

---

src/routes/(console)/project-[project]/databases/database-[database]/table.svelte
src/routes/(console)/project-[project]/databases/table.svelte

Should address: 
* #1525
Manual -
https://github.com/user-attachments/assets/7cbb753b-2d2c-46b3-9d0f-bf46b37998a3
Mentioned above.
Yes.

Fix database & collections Inconsistent ids on page change

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/indexes/overviewIndex.svelte

Remove `icon-x` button in a read-only view

---

src/routes/(console)/organization-[organization]/billing/budgetCap.svelte

- Do not show custom error message when updating budget
- Manual
YES

Fix: show correct error on budget update

---

src/lib/components/billing/selectPaymentMethod.svelte
src/lib/elements/forms/inputNumber.svelte
src/lib/wizards/functions/steps/functionConfiguration.svelte
src/lib/wizards/functions/steps/manualDetails.svelte
src/lib/wizards/functions/steps/templateConfiguration.svelte
src/routes/(console)/createOrganization.svelte
src/routes/(console)/onboarding/+page.svelte
src/routes/(console)/organization-[organization]/billing/addCreditModal.svelte
src/routes/(console)/organization-[organization]/billing/budgetCap.svelte
src/routes/(console)/organization-[organization]/createProject.svelte
src/routes/(console)/organization-[organization]/wizard/step1.svelte
src/routes/(console)/project-[project]/auth/createTeam.svelte
src/routes/(console)/project-[project]/auth/createUser.svelte
src/routes/(console)/project-[project]/auth/security/updatePasswordHistory.svelte
src/routes/(console)/project-[project]/auth/security/updateUsersLimit.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributeForm.svelte
src/routes/(console)/project-[project]/databases/database-[database]/createCollection.svelte
src/routes/(console)/project-[project]/functions/wizard/step1.svelte
src/routes/(console)/project-[project]/messaging/message-[message]/emailMessage.svelte
src/routes/(console)/project-[project]/messaging/topics/create.svelte
src/routes/(console)/project-[project]/messaging/wizard/emailFormList.svelte
src/routes/(console)/project-[project]/storage/bucket-[bucket]/create-file/step1.svelte
src/routes/(console)/project-[project]/storage/create.svelte

Focus inputs when shown conditionally

---

src/routes/(console)/project-[project]/functions/function-[function]/cancel.svelte

Fixes #1495 
You can verify the changes, by adding a deployment to a function, and immediately cancel it. With changes made, you will see the message 'Deployment cancelled' in place of 'Deployment has been deleted'
None
Yes

modify deployment cancel message

---

src/routes/(console)/project-[project]/messaging/wizard/emailFormList.svelte
src/routes/(console)/project-[project]/messaging/wizard/pushFormList.svelte
src/routes/(console)/project-[project]/messaging/wizard/smsFormList.svelte

Fix custom ID not added to messages

---

src/routes/(console)/project-[project]/functions/templates/+page.svelte

Fix: use-case display title casing

---

src/lib/layout/navigation.svelte
src/lib/layout/shell.svelte
src/lib/stores/layout.ts
src/routes/(console)/+layout.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/subNavigation.svelte

This PR fixes [this issue](https://discord.com/channels/564160730845151244/1317347129362223148).
Manual.
Issue linked above.
Yes.

Fix: Create collection modal not showing on mobile

---

playwright.config.ts

test: update e2e endpoint

---

src/routes/(console)/onboarding/+page.svelte

Add spacing

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/indexes/createIndex.svelte

Update default indexing key

---

src/routes/(console)/project-[project]/settings/domains/+page.ts

Fix broken custom domains tab
✅

Fix incorrect resource type

---

src/routes/(console)/project-[project]/sites/site-[site]/settings/deleteModal.svelte

Changes copy. Ignore the branch name.
N/A.
N/A.
Yes.

Fix deletion modal text

---

src/routes/(console)/project-[project]/sites/site-[site]/domains/+page.svelte

Remove the checkboxes on Domains tab in Sites because there's no bulk action there.
Manual.
N/A.
Yes.

Fix domains on sites

---

src/routes/(console)/project-[project]/sites/(components)/deploymentSource.svelte

Fixes excess text overlapping the icon.
Manual.
N/A.
Yes.

Fix tooltip content

---

src/routes/(console)/organization-[organization]/createMember.svelte

Remove roles alert

---

src/routes/(console)/project-[project]/sites/site-[site]/settings/updateRepository.svelte

Fixes incorrect invalidation that caused the wrong feature to be invalidated.
Manual.
N/A.
Yes.

Fix update button not updated on silent mode changes to git config

---

src/routes/(console)/project-[project]/sites/site-[site]/domains/+page.svelte

Fixes text case on button.
Manual.
N/A.
Yes.

Fix: text case on button

---

CONTRIBUTING.md
README.md
src/routes/(console)/project-[project]/sites/(components)/logs.svelte
src/routes/(console)/project-[project]/sites/create-site/deploying/+page.svelte
src/routes/(console)/project-[project]/sites/site-[site]/logs/+page.ts

update: cleaner and better logs for now.
This PR fixes an issue where due to a crash in logging logic, the interaction no longer works.
This also cleans a bit of logs structure while removing `@html` for security, else the console will render anything in logs.
Manual.
https://github.com/user-attachments/assets/6299c2de-132a-4661-acba-64a0eca75a49
N/A.
Yes.

Fix: interaction not working due to a crash

---

src/hooks.client.ts

Disable Sentry replays 

---

package.json
pnpm-lock.yaml

Upgrade console to see new SSR runtime
Manual QA went well, I could create site from Astor template after this change
x
Yes

Feat: Upgrade console SDK

---

src/routes/(console)/organization-[organization]/change-plan/+page.svelte

Top margin based on certain flag moves the cards which doesn't look nice, this PR fixes that.
Before -
https://github.com/user-attachments/assets/6ae25678-cd07-481c-a380-5c924e8849b8
After - 
https://github.com/user-attachments/assets/8de5ec04-3c15-4d30-98c5-f13e597c0e9f
N/A.
Yes.

Fix: layout shift.

---

src/routes/(console)/project-[project]/functions/function-[function]/+page.svelte
src/routes/(console)/project-[project]/sites/site-[site]/deployments/store.ts

Keep terms consistent across functions and sites.
Manual.
Yes.
Yes.

Fix: Size copies

---

package.json
src/routes/(console)/project-[project]/sites/site-[site]/domains/add-domain/+page.svelte

Adds domain tips to sites. Uses Accordion
Manual.
N/A.
Yes.

Add tips for site domains

---

package.json
pnpm-lock.yaml

Update console SDK
All tests should work as usual
Yes

Update Console SDK Version

---

.github/workflows/publish.yml

Fix github secrets

---

src/lib/components/backupRestoreBox.svelte
src/lib/components/migrationBox.svelte
src/lib/pages/domains/create.svelte
src/routes/(console)/project-[region]-[project]/+layout.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/backups/+page.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/+layout.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/+layout.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/deployment-[deployment]/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/executions/+page.svelte
src/routes/(console)/project-[region]-[project]/settings/migrations/+page.svelte

- use project namespace for realtime connections
✅

fix: realtime using project namespace

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/relationship.svelte

Set query limit to 100
* https://github.com/appwrite/console/issues/1519
✅

Set limit to 100

---

src/routes/(console)/project-[project]/databases/database-[database]/backups/table.svelte

Update: Increase backup name column width

---

src/routes/(console)/organization-[organization]/billing/paymentHistory.svelte

Correctly show the payment history, retry options if invoices exists.
Manual.
N/A.
Yes.

Fix: Payment history not visible

---

src/routes/(console)/project-[project]/storage/bucket-[bucket]/settings/+page.svelte

Fixes title case to sentence case, as per Appwrite branding guide
No need
x
Yes

Fix: File extension copy

---

src/lib/charts/legend.svelte

Formats 10000 to 10,000 in database metrics.
Manual.
N/A.
Yes.

Fix: count format

---

package.json
pnpm-lock.yaml
src/lib/components/navbar.svelte
src/lib/components/sidebar.svelte
src/lib/components/support.svelte
src/lib/layout/header.svelte
src/lib/layout/shell.svelte
src/lib/stores/sidebar.ts
src/routes/(console)/+layout.svelte
src/routes/(console)/wizard/support/mobileSupportModal.svelte

Fixes design, dimensions of the support modal on Pink2.
Manual.
Manual.
Yes.

Fix support on PinkV2

---

package.json
pnpm-lock.yaml
src/lib/components/navbar.svelte
src/lib/components/sidebar.svelte
src/lib/helpers/sidebar.ts
src/lib/layout/cover.svelte
src/lib/layout/footer.svelte
src/lib/layout/navigation.svelte
src/lib/layout/shell.svelte
src/lib/stores/viewport.ts
src/routes/+layout.svelte

Feedback on navigation and grid
Yes

Fix feedback onboarding navigation cont

---

src/lib/components/billing/alerts/paymentFailed.svelte
src/lib/layout/containerHeader.svelte
src/lib/stores/billing.ts
src/routes/(console)/project-[project]/+layout.ts

Fixes an issue where a failed invoice would show service limit reached message.
Manual.
N/A.
Yes.

Fix: Misleading alerts on invoice failed

---

src/lib/components/navbar.svelte
src/lib/components/sidebar.svelte
src/lib/layout/shell.svelte
src/routes/(console)/+layout.ts
src/routes/(console)/project-[project]/+page.ts
src/routes/(console)/project-[project]/get-started/+page.svelte
src/routes/(console)/project-[project]/overview/header.svelte
src/routes/(console)/project-[project]/overview/onboard.svelte

Fixes navigation

---

src/lib/components/navbar.svelte
src/routes/+layout.svelte

Update the account menu to show new theme toggle, and user email
https://github.com/user-attachments/assets/b864867f-274f-4162-a5b9-e82856959aa4
✅

Feat wip account menu changes

---

src/routes/(console)/apply-credit/+page.svelte
src/routes/(console)/organization-[organization]/change-plan/+page.svelte

This PR redirects the user to correct path after selecting relevant option when the coupon code validity is verified.
Manual.
https://github.com/user-attachments/assets/6d2c799d-2c3d-45e8-b279-809229164819
N/A.
Yes.

Fix redirections after credits validation

---

src/routes/(console)/organization-[organization]/billing/paymentHistory.svelte
src/routes/(console)/organization-[organization]/invoices/[invoiceId]/download/+page.ts
src/routes/(console)/organization-[organization]/invoices/[invoiceId]/view/+page.ts

- Add route to view PDF invoice
- Add route to download PDF invoice
- Each route validates that invoice exists and then redirects to the REST endpoint
- Manually tested it redirects to correct endpoint upon success
- Manually tested it throws error if invoice doesn't exist
YES

Feat: routes for viewing invoice

---

src/lib/components/navbar.svelte

- use correct naming
- load correct initial theme
✅

Fix theme select

---

package.json
pnpm-lock.yaml
src/routes/+layout.ts

This PR fixes redirects if there are paths + search params in a url when not logged in.
Manual.
N/A.
Yes.

Fix: Redirects

---

package.json
pnpm-lock.yaml
src/lib/pages/domains/wizard/cnameTable.svelte

Show correct domain for cname mapping.
Manual.
N/A.
Yes.

fix: show multi-region cname target.

---

package.json
pnpm-lock.yaml
src/routes/(console)/project-[project]/overview/onboard.svelte
src/routes/(console)/project-[project]/overview/platforms/+page.svelte
src/routes/(console)/project-[project]/overview/platforms/action.svelte
src/routes/(console)/project-[project]/overview/platforms/components/NextjsFrameworkIcon.svelte
src/routes/(console)/project-[project]/overview/platforms/components/NoFrameworkIcon.svelte
src/routes/(console)/project-[project]/overview/platforms/components/NuxtFrameworkIcon.svelte
src/routes/(console)/project-[project]/overview/platforms/components/ReactFrameworkIcon.svelte
src/routes/(console)/project-[project]/overview/platforms/components/SvelteFrameworkIcon.svelte
src/routes/(console)/project-[project]/overview/platforms/components/VueFrameworkIcon.svelte
src/routes/(console)/project-[project]/overview/platforms/components/noFrameworkIcon.svg
src/routes/(console)/project-[project]/overview/platforms/components/noFrameworkIconDark.svg
src/routes/(console)/project-[project]/overview/platforms/createWeb.svelte

Feat add web platform wizard

---

src/routes/(console)/project-[region]-[project]/settings/updateName.svelte

Fix: endpoint as per region

---

src/lib/components/confirm.svelte
src/lib/pages/domains/delete.svelte
src/lib/wizards/functions/createTemplate.svelte
src/routes/(console)/account/delete.svelte
src/routes/(console)/account/deleteMfa.svelte
src/routes/(console)/organization-[organization]/domains/deleteDomainModal.svelte
src/routes/(console)/organization-[organization]/domains/domain-[domain]/certificates/deleteCertificateModal.svelte
src/routes/(console)/project-[project]/functions/create-function/store.ts
src/routes/(console)/project-[project]/functions/create-function/wizard/createTemplate.svelte
src/routes/(console)/project-[project]/overview/platforms/[platform]/delete.svelte
src/routes/(console)/project-[project]/sites/site-[site]/domains/deleteDomainModal.svelte

`Layout.Stack` to fix vertical spacing.
Manual.
N/A.
Yes.

Fix confirm component

---

src/lib/layout/unauthenticated.svelte
src/routes/(console)/apply-credit/+page.svelte
src/routes/(public)/card/helpers.ts

Fix broken campaign image after login.
Manual.
Before -
After -
N/A.
Yes.

Fix: invalid campaign image

---

src/routes/(console)/organization-[organization]/usage/[[invoice]]/totalMembers.svelte

chore: fix avatar on usage list

---

src/lib/commandCenter/panels/ai.svelte
src/routes/(console)/account/deleteAccount.svelte
src/routes/(console)/account/updateName.svelte
src/routes/(console)/organization-[organization]/deleteMember.svelte
src/routes/(console)/organization-[organization]/members/+page.svelte
src/routes/(console)/organization-[organization]/usage/[[invoice]]/totalMembers.svelte
src/routes/(console)/project-[project]/auth/user-[user]/deleteAllSessions.svelte
src/routes/(console)/project-[project]/auth/user-[user]/deleteUser.svelte
src/routes/(console)/project-[project]/auth/user-[user]/updateName.svelte

Even after couple of PRs merged, some cases of userName being left null were left in the console. This PR aims to solve the issue once in for all. Please feel free to inform of any null cases that you can detect that still need to be handled 🙏
Yes.

chore: gracefully handle username being null

---

src/lib/sdk/billing.ts
src/routes/(console)/organization-[organization]/billing/planSummary.svelte

Fixes the issue where if the org. has credits available, they were not shown in payment estimates.
Manual.
N/A.
Yes.

Fix: Credits section not shown

---

src/routes/(console)/project-[project]/overview/platforms/components/AngularFrameworkIcon.svelte
src/routes/(console)/project-[project]/overview/platforms/createWeb.svelte

Add support for the Angular starter kit
✅

Angular starter kit support

---

src/routes/(console)/+layout.ts

Use fallback organization in case url or prefs doesn't specify org id
✅

Use fallback org

---

src/lib/components/modalWrapper.svelte

Fixes the target/topics chooser modal on Safari.
Manual.
Before -
After -
N/A.
Yes.

Fix: Modals on Safari

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/subNavigation.svelte

Update paddings and font styles for the sub navigation
✅

Fix paddings font styling sidebar

---

src/routes/(console)/project-[project]/auth/settings/+page.svelte

Updating Auth methods didn't invalidate the state on Console. 
Fixes #1704.
Manual.
* https://github.com/appwrite/console/issues/1704
Yes.

Fix: Auth states not updating

---

src/lib/layout/usage.svelte
src/routes/(console)/organization-[organization]/usage/[[invoice]]/+page.svelte
src/routes/(console)/organization-[organization]/usage/[[invoice]]/+page.ts

- we haven't considered trailing zeros for accumulated usage charts
https://github.com/user-attachments/assets/8c042722-363c-419f-858b-584d8b6fa9b0
✅

fix: accumulate charts with trailing zeros

---

src/routes/(console)/create-organization/+page.svelte
src/routes/(console)/organization-[organization]/billing/+page.svelte
src/routes/(console)/organization-[organization]/billing/budgetAlert.svelte
src/routes/(console)/organization-[organization]/billing/budgetCap.svelte

Revert "Console Feat: make budget cap nullable"

---

src/lib/components/billing/paymentModal.svelte
src/lib/components/fakeModal.svelte

Fixes the broken payment modal.
Manual.
Before -
After -
N/A.
Yes.

Fix: Payment modal

---

src/lib/stores/database.ts
src/routes/(console)/project-[project]/databases/+page.ts
src/routes/(console)/project-[project]/databases/database-[database]/backups/+page.ts

Lets not call backups related methods if an organization is on a free tier.
Manual.
N/A.
Yepp.

Reduce calls to Backups endpoints

---

src/lib/helpers/string.ts

Allow localhost to web platforms
Manual.
N/A.
Yes.

Allow localhost on web platforms

---

src/routes/(console)/project-[project]/messaging/+page.svelte
src/routes/(console)/project-[project]/messaging/helper.ts
src/routes/(console)/project-[project]/messaging/message-[message]/overview.svelte
src/routes/(console)/project-[project]/messaging/message-[message]/sendModal.svelte
src/routes/(console)/project-[project]/messaging/message-[message]/updateTopics.svelte

Messaging doesn't currently have realtime. Due to this the status is not updated when its sent in the details screen.
This PR fixes that by adding a polling mechanism to messages.
Manual.
N/A.
Yes.

Update message status via polling

---

src/routes/(console)/create-organization/+page.svelte
src/routes/(console)/organization-[organization]/billing/+page.svelte
src/routes/(console)/organization-[organization]/billing/budgetAlert.svelte
src/routes/(console)/organization-[organization]/billing/budgetCap.svelte

Revert "Revert "Console Feat: make budget cap nullable""

---

package.json
pnpm-lock.yaml
src/lib/commandCenter/panels/ai.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/float.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/integer.svelte

The params passed to SDK for integer and float attributes' updates were in wrong order, hence causing a failure and error from backend.
Manual.
N/A.
Yes.

Fix: Wrong params sent for updates

---

src/lib/actions/analytics.ts
src/lib/helpers/utm.ts
src/routes/+layout.svelte

Automatically add utm info to tracking events
✅

Send utm info to analytics

---

src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/attributes/integer.svelte

Check if integer value is exceeding the allowed limit. If so, omit from object sent. Since it's a PATCH call, it will still work!
✅

Fix big int issue

---

src/routes/(console)/project-[project]/databases/database-[database]/+layout.svelte

Fixes shortcuts.
Manual.
* https://github.com/appwrite/console/issues/1493
Yes.

Fix shortcuts

---

src/lib/layout/createProject.svelte
src/routes/(console)/onboarding/create-project/+page.svelte
src/routes/(console)/organization-[organization]/createProjectCloud.svelte

Move the submit button outside the component so it can be in the footer of the modal when creating a new project.
✅

Fix: move create project submit button to modal button

---

src/lib/layout/wizard.svelte
src/routes/(console)/project-[project]/overview/platforms/components/JavascriptFrameworkIcon.svelte
src/routes/(console)/project-[project]/overview/platforms/components/index.ts
src/routes/(console)/project-[project]/overview/platforms/createWeb.svelte

Improvements for showing correct start and env vars
✅

Fix feedback create web flow

---

src/lib/stores/billing.ts
src/lib/stores/organization.ts
src/routes/(console)/organization-[organization]/billing/budgetCap.svelte
src/routes/(console)/organization-[organization]/budgetLimitAlert.svelte

- Show budget limit alert with CTA to update budget cap
YES

Feat: show budget limit alert

---

src/routes/(console)/organization-[organization]/billing/retryPaymentModal.svelte

Extra dollar symbol removed
Open retry payment modal
https://github.com/appwrite/console/issues/1662
Yes

Fix extra dollar symbol removed

---

package.json
pnpm-lock.yaml
src/lib/components/sidebar.svelte

Fixes expand/collapse nudge showing through/behind other content
✅

fix-expand-collapse-sidebar-nudge

---

src/lib/components/heading.svelte
src/lib/sdk/billing.ts
src/lib/stores/billing.ts
src/lib/stores/organization.ts
src/routes/(console)/organization-[organization]/billing/+page.svelte
src/routes/(console)/organization-[organization]/billing/paymentHistory.svelte
src/routes/(console)/organization-[organization]/billing/retryPaymentModal.svelte
src/routes/(console)/organization-[organization]/teamReadonlyAlert.svelte

- Validate payment after live retry for failed invoice
- Previously relied in weebhook to update the invoice status
- Will immediately update the invoice status to reflect the payment status
YES

Feat: validate live payment

---

src/lib/components/heading.svelte
src/routes/(console)/project-[project]/auth/security/updatePasswordHistory.svelte

Fixes a bug -
Manual.
N/A.
Yes.

Fix tabs not clickable

---

src/lib/stores/sdk.ts

Set mock API endpoint during build time

---

src/lib/stores/sdk.ts

Fix API endpoint prioritization order

---

src/routes/(console)/apply-credit/+page.svelte

Fixes an issue where credits were not applied and not shown to an existing Pro org.
Manual.
N/A.
Yes.

Fix: credits not applied

---

src/routes/(console)/project-[project]/storage/bucket-[bucket]/create-file/step1.svelte
src/routes/(console)/project-[project]/storage/bucket-[bucket]/settings/+page.ts
src/routes/(console)/project-[project]/storage/bucket-[bucket]/settings/updateMaxFileSize.svelte

Fixes file upload on self-hosted because there's no `$currentPlan` there!

Fix file upload on self-hosted

---

src/lib/layout/containerHeader.svelte
src/lib/stores/billing.ts
src/routes/(console)/organization-[organization]/members/+page.svelte

Show correct plan limitations on members page.
Manual.
Before -
After -

Fix: showing invite on a free plan

---

src/lib/layout/containerHeader.svelte
src/routes/(console)/organization-[organization]/members/+page.svelte

Fixes an issue where the paid plans would show `PHP_INT_MAX` as a limit on members info. pill
Manual.
Before -
After -
* #1778 
Yes.

Fix: paid plans showing `PHP_INT_MAX` for limits

---

src/lib/components/feedback/feedback.svelte
src/lib/stores/feedback.ts
src/routes/(console)/project-[project]/settings/migrations/exportModal.svelte
src/routes/(console)/wizard/feedback/step1.svelte

Include:
- billing plan
- org id
- proejct id
- user id
This will help us prioritize feedback better and give us info about the org and project so we can dig in if needed.
Manually submitted feedback and confirmed the feedback was stored successfully.
None
Yes

feat: update feedback to include additional data

---

src/lib/components/searchQuery.svelte

Fixes an issue where the letters are cut off while typing, resulting an invalid or half-baked search string.
Manual.
https://github.com/user-attachments/assets/2d0864b0-33ab-489d-b1b9-2a0fe381bfcb
N/A.
Yes.

Fix: search x debounce

---

src/routes/(console)/project-[project]/settings/migrations/(import)/step1.svelte

Fix: set appwrite as label

---

package.json
pnpm-lock.yaml
src/lib/components/dualTimeView.svelte
src/lib/components/filters/filters.svelte
src/lib/components/menu/menu.svelte
src/lib/components/menu/store.ts
src/lib/components/sidebar.svelte
src/lib/elements/forms/inputFilePicker.svelte
src/routes/(console)/project-[project]/auth/+page.svelte
src/routes/(console)/project-[project]/auth/user-[user]/identities/+page.svelte
src/routes/(console)/project-[project]/auth/user-[user]/targets/+page.svelte
src/routes/(console)/project-[project]/databases/+page.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/+page.svelte
src/routes/(console)/project-[project]/functions/+page.svelte
src/routes/(console)/project-[project]/messaging/+page.svelte
src/routes/(console)/project-[project]/messaging/create-[type]/(type)/email.svelte
src/routes/(console)/project-[project]/messaging/create-[type]/(type)/push.svelte
src/routes/(console)/project-[project]/messaging/message-[message]/pushMessage.svelte
src/routes/(console)/project-[project]/messaging/message-[message]/scheduleModal.svelte
src/routes/(console)/project-[project]/messaging/message-[message]/sendModal.svelte
src/routes/(console)/project-[project]/messaging/providers/+page.svelte
src/routes/(console)/project-[project]/messaging/topics/+page.svelte
src/routes/(console)/project-[project]/messaging/topics/topic-[topic]/+page.svelte
src/routes/(console)/project-[project]/messaging/topics/topic-[topic]/table.svelte
src/routes/(console)/project-[project]/storage/+page.svelte

Fix multiple feedback

---

src/routes/(console)/project-[project]/databases/database-[database]/+layout.svelte

Fix: plans <> backupsEnabled

---

src/lib/sdk/billing.ts
src/routes/(console)/organization-[organization]/billing/budgetAlert.svelte
src/routes/(console)/organization-[organization]/billing/budgetCap.svelte

- Plan config for budget cap
YES

Feat: budget cap config update

---

package.json
pnpm-lock.yaml
src/lib/stores/oauth-providers.ts

Adds figma to list of oauth providers.
-  https://github.com/appwrite/appwrite/pull/9623
Yes.

feat: add figma to list of oauth adapters

---

src/lib/constants.ts
src/lib/helpers/project.ts

Dashes to Subdomains

---

src/lib/components/billing/paymentModal.svelte
src/lib/components/fakeModal.svelte
src/lib/components/permissions/permissions.svelte
src/lib/stores/stripe.ts
src/routes/(console)/organization-[organization]/billing/paymentMethods.svelte
src/routes/(console)/project-[project]/databases/database-[database]/+page.svelte
src/routes/(console)/project-[project]/databases/database-[database]/backups/upgradeCard.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/create/+page.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/email.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/integer.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/string.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/url.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/delete.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/indexes/createIndex.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/settings/displayName.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/settings/updatePermissions.svelte
src/routes/(console)/project-[project]/databases/database-[database]/collection-[collection]/table.svelte
src/routes/(console)/project-[project]/databases/database-[database]/delete.svelte

Cleanup and fixes.
Manual.
N/A.
Yes.

Console fixes for 1.7.x

---

playwright.config.ts
src/lib/components/permissions/permissions.svelte

Hides the overflow ugly scrollbar in permissions component.
Manual.
N/A.
Yes.

Fix: hide the scrollbar in permissions

---

package.json
pnpm-lock.yaml
src/lib/sdk/billing.ts
src/lib/stores/organization.ts
src/routes/(console)/organization-[organization]/+page.svelte
src/routes/(console)/organization-[organization]/createProject.svelte
src/routes/(console)/organization-[organization]/wizard/step2.svelte

Shows `upgrade` if the plan doesn't support additional regions.
Manual.
N/A.
Yes.

Show upgrade for more regions

---

src/routes/(console)/organization-[organization]/wizard/step2.svelte

Fixes availability checks to better represent current state of backend
None
x
Yes

Fix: Multiregion project creation

---

src/routes/(console)/organization-[organization]/wizard/step2.svelte

Reverts appwrite/console#1798
fixes country each key

Revert "Fix: Multiregion project creation"

---

src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/+page.svelte
src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/+page.ts

- remove usage limits from bucket view
- maunal
✅

Remove organization storage usage from bucket view

---

src/lib/stores/organization.ts
src/routes/(console)/organization-[organization]/wizard/step2.svelte

fix: region logic in wizard

---

src/lib/actions/analytics.ts
src/lib/elements/forms/inputSelectCheckbox.svelte
src/lib/layout/notifications.svelte
src/routes/(console)/project-[project]/databases/database-[database]/+page.svelte
src/routes/(console)/project-[project]/databases/database-[database]/backups/containerHeader.svelte
src/routes/(console)/project-[project]/databases/database-[database]/backups/createPolicy.svelte
src/routes/(console)/project-[project]/databases/database-[database]/backups/policy.svelte
src/routes/(console)/project-[project]/databases/database-[database]/backups/table.svelte

Fixes to misc designs on `Databases#Backups` section.
Manual.
N/A.
Yes.

Databases design fixes

---

src/routes/(console)/project-[region]-[project]/auth/templates/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/usage/[[period]]/+page.svelte
src/routes/(console)/project-[region]-[project]/settings/usage/[[invoice]]/+page.svelte

Fix: urls as per region.

---

docker/nginx.conf

- disables cache on `/console/service-worker.js`
✅

fix: disable cache for service-worker.js

---

src/routes/(console)/apply-credit/+page.svelte

Added improved check for updating the billing plan. It now checks the plan order to prevent unwanted downgrades.
When applying the campaign results in the same plan the organisation is already on (or lower), the user will see this. And nothing will change in the plan of the organisation.
(screenshot shows a SCALE org with a PRO plan campaign)
When applying the campaign results in an upgrade, the user will be shown the campaign text in the estimated total box:
(screenshot shows a PRO org with a SCALE plan campaign)
✅

Fix: correct apply credit flow on main

---

src/lib/pages/domains/create.svelte

Domains subscribed incorrectly and did not check the event/channels on message

Fix domains realtime

---

src/routes/(console)/organization-[organization]/wizard/step2.svelte

**only on Firefox**
Before:
https://github.com/user-attachments/assets/691ea5a0-9c96-4de9-98b1-7d7171686428
After:
https://github.com/user-attachments/assets/e3c9d055-0e87-4172-9736-b87a73728221
Yes

Fix: regions jumping around on Firefox

---

src/routes/(console)/organization-[organization]/usage/[[invoice]]/+page.svelte

Fix graph summation
Same change as for main: https://github.com/appwrite/console/pull/1826
Yes

Fix: Show the summation of the graph, not the totals

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/+page.svelte

Add internal attributes to filter.
Manual.
N/A.
Yes.

Add support for filter by `$id`, `$createdAt`, and `$updatedAt` on documents

---

src/routes/(console)/organization-[organization]/billing/retryPaymentModal.svelte

Check if the invoice status is succeeded or cancelled, confirm if not either of those.
N/A.
N/A.
Yes.

Update confirmation logic

---

.github/workflows/publish.yml
docker/nginx.conf

Add: max-age for `env`

---

src/lib/stores/sdk.ts
src/lib/system.ts

Additional check with hostname

---

src/routes/(console)/project-[region]-[project]/auth/teams/+page.svelte
src/routes/(console)/project-[region]-[project]/auth/teams/team-[team]/members/+page.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/subNavigation.svelte

* fix(databases): ensure collection subnavigation includes region
* fix(auth): fix missing region in team members and teams links
None
None
Yes

Fix missing region

---

src/lib/components/bottomModalAlert.svelte
src/routes/(console)/bottomAlerts.ts
src/routes/(console)/onboarding/create-project/+page.svelte
src/routes/(public)/template-[template]/+page.svelte

More fixes

---

src/routes/(console)/organization-[organization]/domains/retryDomainModal.svelte

fix: change notification type from error to success for domain verification

---

pnpm-lock.yaml

chore: update packages

---

src/hooks.client.ts
src/hooks.server.ts
src/lib/components/domains/recordTable.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/recordsCard.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/retryDomainModal.svelte
src/routes/(console)/project-[region]-[project]/settings/domains/retryDomainModal.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/retryDomainModal.svelte

Fix success message in domain verification modals

---

src/lib/components/sidebar.svelte
src/lib/stores/roles.ts
src/lib/system.ts
src/routes/(console)/organization-[organization]/header.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/+page.svelte
src/routes/(console)/project-[region]-[project]/overview/+layout.svelte
src/routes/(console)/project-[region]-[project]/settings/domains/add-domain/verify-[domain]/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/table.svelte
src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/file-[file]/+page.svelte

Remove feature flag and add dns state for verifying

---

src/routes/(console)/organization-[organization]/domains/domain-[domain]/table.svelte

Add locked DNS record indication and type safety

---

src/lib/system.ts
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/+page.svelte

Hide: csv imports, show conditionally.

---

src/lib/components/domains/recordTable.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/retryDomainModal.svelte

Use correct env var for CNAME record on sites.

---

src/lib/actions/analytics.ts
src/routes/(console)/project-[region]-[project]/functions/function-[function]/executions/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/executions/table.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/table.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/deployments/table.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/logs/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/logs/store.ts
src/routes/(console)/project-[region]-[project]/sites/site-[site]/logs/table.svelte

Adds batch deletes to -
* Functions:
- Executions
- Deployments
* Sites:
- Logs
- Deployments
Manual.
N/A.
Yes.

Add batch deletes to Functions, Sites.

---

src/lib/components/menu/menu.svelte
src/lib/components/menu/store.ts
src/lib/components/menu/subMenu.svelte
src/routes/(console)/organization-[organization]/header.svelte
src/routes/(console)/project-[region]-[project]/functions/create-function/template-[template]/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/(modals)/redeployModal.svelte
src/routes/(console)/project-[region]-[project]/settings/updateName.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/deployments/deployment-[deployment]/+page.svelte

Misc fixes

---

src/lib/sdk/billing.ts
src/routes/(console)/project-[region]-[project]/functions/create-function/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/(modals)/createManual.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/deployments/createManualDeploymentModal.svelte

Fix upload limit

---

src/lib/elements/forms/inputCron.svelte

Fix the Cronjob input being a type email which it shouldn't be.
✅

Cronjob field as text

---

src/lib/stores/domains.ts
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/+page.ts
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/deleteDomainModal.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/recordsCard.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/retryDomainModal.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/table.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/+page.ts
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/deleteDomainModal.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/retryDomainModal.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/table.svelte

Update domain types

---

src/lib/stores/sdk.ts

Includes port in API endpoint, so custom ports (not 80) worls
Multiple discord threads, including:
- https://discord.com/channels/564160730845151244/1375575246370766908
- https://discord.com/channels/564160730845151244/1375547722245083286
- https://discord.com/channels/564160730845151244/1373993914532495420
Yes

Fix: Self-hosted ports

---

src/routes/(console)/account/sessions/+page.svelte

Fixes freeze, and layout issues. Freeze reported by community member:
Before:
1. Freezing issues
2. Layout issues
After:
https://discord.com/channels/564160730845151244/1375939435321098373
Yes

Fix: Sessions list

---

package.json
pnpm-lock.yaml
src/routes/(console)/project-[region]-[project]/sites/create-site/store.ts

Related to: https://github.com/appwrite/console/pull/1888

Chore: Push forgotten commit

---

package.json
pnpm-lock.yaml
src/routes/(console)/organization-[organization]/+page.svelte

- that check was writing to a store and was buggy at all times, with svelte 5 this actually worked and caused an infinite loop - since each project writes to the same store
- also updates pink to have better fallback fonts
✅

Remove unused service disabled check from organization page

---

package.json
pnpm-lock.yaml
src/routes/(console)/organization-[organization]/domains/domain-[domain]/domainMetrics.svelte

Fix domain status

---

package.json
pnpm-lock.yaml

Update @appwrite.io/pink-svelte to commit 4b27c82

---

src/routes/(console)/+layout.svelte
src/routes/(console)/onboarding/create-organization/+page.svelte
src/routes/(console)/organization-[organization]/settings/deleteOrganizationModal.svelte

Deleting the only org created another on onboarding in the bg, this fixes it.
Manual.
N/A.
Yes.

Add: create an organization page

---

src/lib/helpers/regions.ts
src/lib/layout/createProject.svelte
src/routes/(console)/(migration-wizard)/index.ts
src/routes/(console)/(migration-wizard)/resource-form.svelte
src/routes/(console)/(migration-wizard)/wizard.svelte
src/routes/(console)/project-[region]-[project]/settings/migrations/(import)/importReport.svelte
src/routes/(public)/template-[template]/+page.svelte

Migrate the migration flow to Pink2

---

src/routes/(console)/project-[region]-[project]/auth/templates/emailSignature.svelte

Before -
After -
Manual.
N/A.
Yes.

Fix: image.

---

src/lib/system.ts
src/routes/(console)/organization-[organization]/domains/+page.ts
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/add-domain/+page.ts
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/add-domain/verify-[domain]/+page.ts
src/routes/(console)/project-[region]-[project]/settings/domains/add-domain/+page.ts
src/routes/(console)/project-[region]-[project]/settings/domains/add-domain/verify-[domain]/+page.ts
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/add-domain/+page.ts
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/add-domain/verify-[domain]/+page.ts

Fix domain queries

---

src/routes/(public)/(guest)/register/+page.svelte
src/routes/+page.ts

The account was invalidated too soon during registration, leading to weird behaviour

fix: credits wrong redirection

---

src/routes/(console)/onboarding/create-project/+page.svelte
src/routes/(console)/onboarding/create-project/+page.ts

Always redirect to create-org after onboarding is completed once

---

src/lib/components/billing/validateCreditModal.svelte
src/routes/(console)/apply-credit/+page.svelte
src/routes/(console)/create-organization/+page.svelte
src/routes/(console)/create-organization/+page.ts
src/routes/(console)/organization-[organization]/change-plan/+page.svelte
src/routes/(console)/organization-[organization]/change-plan/+page.ts

Ensure any applied coupons are included in the request to change plan so that the credit is used as expected.
Manually tested change plan w/ and w/o a coupon
None
Yes

Fix coupon not applying

---

src/lib/components/domains/cnameTable.svelte
src/lib/components/domains/nameserverTable.svelte
src/lib/components/domains/recordTable.svelte
src/lib/components/usageCard.svelte
src/routes/(console)/organization-[organization]/domains/+page.svelte
src/routes/(console)/organization-[organization]/domains/domain-[domain]/+page.ts
src/routes/(console)/organization-[organization]/domains/domain-[domain]/domainMetrics.svelte
src/routes/(console)/organization-[organization]/domains/recordsCard.svelte
src/routes/(console)/organization-[organization]/domains/retryDomainModal.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/add-domain/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/add-domain/verify-[domain]/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/retryDomainModal.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/table.svelte
src/routes/(console)/project-[region]-[project]/settings/domains/add-domain/+page.svelte
src/routes/(console)/project-[region]-[project]/settings/domains/add-domain/verify-[domain]/+page.svelte
src/routes/(console)/project-[region]-[project]/settings/domains/retryDomainModal.svelte
src/routes/(console)/project-[region]-[project]/settings/domains/table.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/add-domain/verify-[domain]/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/createPreviewDomainModal.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/retryDomainModal.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/table.svelte

- Change verified prop from boolean to boolean|undefined to better represent three-state verification (undefined/pending, true/verified, false/failed). 
- Remove "Pending verification" badges and standardize verification error messages. 
- Fix grid layout for domain metrics 
- Improve error handling by displaying error messages instead of error objects.

Refactor domain verification status handling

---

src/routes/(console)/organization-[organization]/domains/domain-[domain]/table.svelte

Centers the lock and the actions menu icon.
Manual.
N/A.
Yes.

Fix: icon alignment

---

src/lib/components/git/repositories.svelte

Fix selecting different Github installation
Before:
https://github.com/user-attachments/assets/8ba2818d-1f4b-41ae-98f5-556427ce1163
After:
https://github.com/user-attachments/assets/1baa72c5-a793-4cd4-9320-9663eb9d998c
✅

Only untrack when no installation is set

---

src/lib/components/paginationInline.svelte
src/lib/components/permissions/team.svelte
src/lib/components/permissions/user.svelte

Context - https://discord.com/channels/564160730845151244/564160731327758347/1378271349918662696
Manual.
Added above.
Yes.

Fix: teams/users pagination

---

src/lib/helpers/domains.ts
src/lib/helpers/tlds.ts
src/routes/(console)/organization-[organization]/domains/domain-[domain]/createRecordModal.svelte
src/routes/(console)/organization-[organization]/domains/domain-[domain]/updateRecordModal.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/add-domain/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/+page.ts
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/add-domain/+page.svelte

Fix missing rules (redirect)
remove double protocol
improve placeholders for dns records
fix www subdomain rules
Manual QA

Fix: Rules edge cases

---

src/routes/(console)/project-[region]-[project]/sites/+page.ts
src/routes/(console)/project-[region]-[project]/sites/site-[site]/+layout.ts

Fix: sites to be public

---

src/lib/components/git/repositories.svelte

Fix responsiveness

---

src/routes/(console)/organization-[organization]/change-plan/+page.svelte

This will allow adding credits when upgrading.
Manual
Parent PR:
* https://github.com/appwrite/console/pull/1973
Yes

fix: update Change plan to show Payment box when upgrading

---

package.json
pnpm-lock.yaml

Bump pink-svelte

---

src/lib/components/billing/discountsApplied.svelte

Fix: typography color

---

src/routes/(console)/organization-[organization]/change-plan/+page.svelte
src/routes/(console)/regions.ts

Reload regions on upgrades

---

src/routes/(console)/project-[region]-[project]/settings/migrations/+page.svelte

The link should point to the docs for migrating from Cloud.
None
None
Yes

fix(migrations): update link for exporting to self-hosted instance

---

src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/retryDomainModal.svelte

Move the alert to a notification

Move retry to alert

---

.github/workflows/publish.yml

Fix build cicd syntax

---

package.json
pnpm-lock.yaml
src/lib/commandCenter/panels/ai.svelte

Fix AI alert and button alignment

---

package.json
pnpm-lock.yaml
src/routes/(console)/project-[region]-[project]/functions/function-[function]/domains/add-domain/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/+page.ts
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/add-domain/+page.svelte

Fix domains

---

src/lib/components/navbar.svelte

https://github.com/user-attachments/assets/f6ca1a26-35c8-43f8-84db-01a9479b485f

fix: navbar dropdown (close on esc)

---

src/lib/stores/user.ts

Fix: store null on onboarding

---

package.json
pnpm-lock.yaml
src/lib/components/columnSelector.svelte

Fix the added whitespace below the footer when the contents of a Popover is bigger than the available height.
Before:
https://github.com/user-attachments/assets/4c30461b-a0d0-45c0-8544-9e9277cb6a9e
After:
https://github.com/user-attachments/assets/197c9eb8-c049-426a-a013-1bff484ea696
✅

fix popover overflowing page

---

src/lib/components/navbar.svelte

Fix: account menu click not working

---

src/routes/(console)/project-[region]-[project]/functions/create-function/(components)/aside.svelte
src/routes/(console)/project-[region]-[project]/functions/create-function/(components)/details.svelte
src/routes/(console)/project-[region]-[project]/functions/create-function/repository-[repository]/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/create-function/repository-[repository]/+page.ts
src/routes/(console)/project-[region]-[project]/sites/create-site/repositories/repository-[repository]/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/create-site/repositories/repository-[repository]/+page.ts

Before -
After -
Manual.
N/A.
Yes.

Fix detections not called on functions

---

src/lib/components/git/repositories.svelte

Fix the combobox now showing the possible options
✅

Removing await function to fix the combobox select options

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/document-[document]/+page.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/relationship.svelte

https://github.com/user-attachments/assets/bda8e181-ee1f-4183-ab16-21f2e42e5ff2
Manual.
N/A.
Yes.

Fix: relationship selection issues

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/table.svelte

Before -
After -
Manual.
N/A.
Yes.

Fix: time display regression on tables

---

src/routes/(console)/organization-[organization]/billing/budgetCap.svelte

Remove html from notification

---

src/routes/(console)/organization-[organization]/domains/domain-[domain]/importRecordModal.svelte
src/routes/(console)/project-[region]-[project]/functions/create-function/manual/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/(modals)/createManual.svelte
src/routes/(console)/project-[region]-[project]/messaging/providers/settingsFormInput.svelte
src/routes/(console)/project-[region]-[project]/sites/create-site/manual/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/create-site/manual/+page.ts
src/routes/(console)/project-[region]-[project]/sites/create-site/store.ts
src/routes/(console)/project-[region]-[project]/sites/site-[site]/deployments/createManualDeploymentModal.svelte
src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/create/+page.svelte

(missing file, domain configuration)
Manual QA
x
Yes

Fix manual deployment flows 

---

src/routes/(console)/organization-[organization]/change-plan/+page.svelte

record more info for billing feedback
yes.

chore: record more info in billing feedback

---

src/lib/stores/billing.ts
src/routes/(console)/project-[region]-[project]/+layout.ts

Fix: checks on non-base plans

---

src/routes/(console)/project-[region]-[project]/functions/function-[function]/usage/[[period]]/+page.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/usage/[[period]]/+page.ts

Fix: usage calc on function.

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/+page.svelte

This was added before, but must have regressed due to merge conflicts.
We still have more fixes needed for this documents filter.
Fixes https://github.com/appwrite/console/issues/2057
* https://github.com/appwrite/console/pull/1837
Yes

fix: add $id, $createdAt, and $updatedAt to documents filter

---

src/routes/(console)/project-[region]-[project]/+layout.ts

Fixes - https://github.com/appwrite/console/pull/2043#issuecomment-3017119294
Manual.
Before -
After -
* https://github.com/appwrite/console/pull/2043#issuecomment-3017119294
Yes.

Fix: plan check on self hosted

---

src/lib/components/billing/validateCreditModal.svelte
src/lib/components/feedback/evaluation.svelte
src/lib/components/feedback/feedbackGeneral.svelte
src/lib/components/modal.svelte
src/lib/components/navbar.svelte
src/lib/components/sidebar.svelte
src/lib/layout/createProject.svelte
src/routes/(console)/create-organization/+page.svelte
src/routes/(console)/onboarding/create-organization/+page.svelte
src/routes/(console)/onboarding/create-project/+page.svelte
src/routes/(console)/organization-[organization]/createMember.svelte
src/routes/(console)/organization-[organization]/domains/add-domain/+page.svelte
src/routes/(console)/organization-[organization]/domains/domain-[domain]/createRecordModal.svelte
src/routes/(console)/organization-[organization]/members/+page.svelte
src/routes/(console)/project-[region]-[project]/auth/+page.svelte
src/routes/(console)/project-[region]-[project]/auth/createUser.svelte
src/routes/(console)/project-[region]-[project]/auth/teams/team-[team]/createMembership.svelte
src/routes/(console)/project-[region]-[project]/messaging/create-[type]/(type)/email.svelte
src/routes/(console)/project-[region]-[project]/messaging/create-[type]/(type)/push.svelte
src/routes/(console)/project-[region]-[project]/messaging/create-[type]/(type)/sms.svelte
src/routes/(console)/project-[region]-[project]/overview/platforms/createWeb.svelte
src/routes/(console)/project-[region]-[project]/settings/domains/add-domain/+page.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/domains/createPreviewDomainModal.svelte
src/routes/(console)/project-[region]-[project]/storage/+page.svelte
src/routes/(console)/project-[region]-[project]/storage/create.svelte

Implements a dual focus strategy for modals using both `autofocus` attribute and `onMount` focus handling. This ensures reliable input focus across different scenarios (initial load and dynamic content) and improves keyboard accessibility.
1. Initial page load:
- Open any modal with input field
- Verify first input is focused automatically
2. Dynamic content:
- Open modals through user interactions
- Verify input focus works when modal opens
- Test with keyboard navigation
3. Browser testing:
- Tested on Chrome, Firefox, Safari
- Verified no double-focus effects occur
Fixes #1882 - Modal focus not working consistently
Yes

fix: improve modal focus

---

package.json
pnpm-lock.yaml
src/lib/components/git/productionBranchFieldset.svelte
src/lib/components/git/selectRootModal.svelte
src/routes/(console)/project-[region]-[project]/functions/function-[function]/settings/updateRepository.svelte
src/routes/(console)/project-[region]-[project]/sites/site-[site]/settings/updateRepository.svelte

- Update SDK
- Pass `branch` to `getRepositoryContents` method
Tested manually

Update SDK and pass branch to getRepositoryContents

---

src/lib/components/bottomModalAlert.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/attributes/deleteAttribute.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/createAttribute.svelte

1. Fix a leftover from https://github.com/appwrite/console/pull/2076
2. Improve the bottom promo modal to -
- fix modal complete hide on the last item cta click
- move to svelte5 runes synatx

Minor patch for column selection and bottom promo modal

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/attributes/string.svelte

Fix: cursor and editable behaviour

---

src/lib/commandCenter/panels/ai.svelte

fixes rendering of lists in assistant
before:
after:
yes.

fix: rendering of lists in assistant

---

package.json
pnpm-lock.yaml
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/table.svelte

Fix: table selections, popovers on table cells.

---

src/routes/(console)/bottomAlerts.ts

Hide promo

---

src/lib/components/sidebar.svelte

Chore: Change sites copy

---

src/lib/stores/billing.ts
src/routes/(console)/onboarding/create-project/+page.svelte

Fix create project.
Manual -
https://github.com/user-attachments/assets/872f8c0f-2dda-4566-81e2-3b16c8d16a21
N/A.
Yes.

Fix: onboarding flow.

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/boolean.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/email.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/integer.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/string.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/url.svelte

Fixes the input's nullable state when an attribute/column is not a required type.
Manual.
N/A.
Yes.

Fix: the nullable type on inputs

---

package.json
pnpm-lock.yaml

Upgrades eslint to prevent potential vulnerability
Tests must pass
x
Yes

Fix: Vuln scan report

---

src/routes/(console)/organization-[organization]/billing/billingAddress.svelte
src/routes/(console)/organization-[organization]/billing/paymentMethods.svelte

Fix: unnecessary dividers.

---

package.json
pnpm-lock.yaml
src/routes/(console)/project-[region]-[project]/auth/templates/email2FATemplate.svelte
src/routes/(console)/project-[region]-[project]/auth/templates/emailOtpSessionTemplate.svelte
src/routes/(console)/project-[region]-[project]/auth/templates/emailTemplate.svelte
src/routes/(console)/project-[region]-[project]/auth/templates/store.ts

Adds all the required and relevant options on templates for use.
Manual.
* https://github.com/appwrite/appwrite/issues/7916
* https://github.com/appwrite/appwrite/pull/10170
Yes.

Fix: auth templates

---

.github/workflows/publish.yml

Feat: Enable sites on Cloud

---

src/lib/components/filters/content.svelte

Fixes filter persistence:
Applied filters are now visible after you apply them and remain visible even after a page refresh.
Allows multiple filters:
You can now add more than one filter at a time. Previously, adding a second filter would remove the first; now, all filters are retained and visible.
yes

fix: broken filter issue

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/+layout.svelte

Quick fix on databases page.

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/document-[document]/attributes/store.ts

Without this, processing/failed relationship attributes will result in 400 error.
None
None
Yes

fix: fetch available relationship attributes

---

src/routes/(console)/organization-[organization]/billing/paymentHistory.svelte

Users can delete organizations with abandoned invoices, but give them the option to pay their outstanding invoices in the Console.
Manual
None
Yes

feat: allow retrying abandoned invoices

---

src/routes/(console)/organization-[organization]/domains/domain-[domain]/domainMetrics.svelte

Fix: status update for domains

---

src/lib/components/csvImportBox.svelte

Fixes an issue where the CSV import status was not working on other regions.
Manual.
https://github.com/user-attachments/assets/84f59a7a-1671-47a6-a6e8-afcf339d31d0
N/A.
Yes.

Fix: CSV realtime status

---

src/routes/(console)/project-[region]-[project]/overview/platforms/+page.svelte

add another column named App identifer

feat: added a column named  Identifier

---

src/lib/components/sidebar.svelte

add responsivness for settings button on ipad too
yes

fix:added support for tablet too

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/collection-[collection]/attributes/relationship.svelte

resolve relationship attribute update issues
yes

Fix: bug updating relationships

---

src/routes/(console)/project-[region]-[project]/overview/platforms/createAndroid.svelte
src/routes/(console)/project-[region]-[project]/overview/platforms/createApple.svelte

Improve onboarding guides for Apple and Android to show correct values of env vars.

Fix apple and android onboarding guides

---

src/routes/(console)/project-[region]-[project]/functions/function-[function]/settings/updateBuildCommand.svelte

Always pass the user-selected `specification` to the update API
yes

fix: Build command update fix

---

src/routes/(public)/invite/+page.svelte

Updates the success notification shown after accepting an organization/team invite from “Successfully logged in.” to “Successfully joined the organization.”
yes

fix: changed the message from Successfully logged in 

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/+layout.svelte

Fix: simplify copy

---

src/routes/(console)/project-[region]-[project]/overview/platforms/createReactNative.svelte

Fix steps in onboarding guide for react native.

Fix console commands

---

src/routes/(console)/project-[region]-[project]/overview/platforms/createAndroid.svelte
src/routes/(console)/project-[region]-[project]/overview/platforms/createApple.svelte
src/routes/(console)/project-[region]-[project]/overview/platforms/createFlutter.svelte

Update android, apple and flutter onboarding guides to show endpoint.

Show endpoint on cloud as well

---

src/routes/(console)/project-[region]-[project]/sites/+page.svelte

Correct duplicated wording in Sites intro message
Before:
After:
yes

fix: typo in sites onboarding

---

src/lib/helpers/regions.ts

chore: fix region sorting to prioritise available instead of disabled

---

src/lib/components/billing/alerts/projectsLimit.svelte
src/lib/components/billing/alerts/selectProjectCloud.svelte
src/lib/components/breadcrumbs.svelte
src/lib/components/navbar.svelte
src/lib/layout/shell.svelte
src/lib/stores/billing.ts
src/routes/(console)/+layout.svelte
src/routes/(console)/+layout.ts
src/routes/(console)/organization-[organization]/+page.svelte
src/routes/(console)/organization-[organization]/createProjectCloud.svelte

Only load projects list when necessary.
Manual.
N/A.
Yes.

Optimize projects loading

---

package.json
pnpm-lock.yaml
src/lib/stores/preferences.ts
src/routes/(console)/+layout.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/+layout.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/layout/sidesheet.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/rows/columns/types/relationship.svelte
src/routes/(console)/project-[region]-[project]/functions/create-function/repository-[repository]/+page.svelte
src/routes/(console)/project-[region]-[project]/messaging/providers/provider-[provider]/dangerZone.svelte

Fix: broken relationships on sheets due to missing selects

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/spreadsheet.svelte

Fix: row height, truncate header name

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/spreadsheet.svelte

Show numbers in comma format and not in abbreviated format

---

package.json
pnpm-lock.yaml
src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/rows/editRelated.svelte
src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/spreadsheet.svelte

update: scroll logic for load next page.

Fix: logic for relationships, multiple items

---

src/lib/components/sidebar.svelte
src/lib/layout/shell.svelte

Fix inert pages from sidebar state.

revert changes to sidebar

---

package.json
pnpm-lock.yaml
src/routes/(console)/project-[region]-[project]/functions/function-[function]/executions/execute-function/+page.svelte

feat: allow HEAD function executions

---

src/lib/components/sidebar.svelte
src/lib/helpers/sidebar.ts
src/lib/layout/shell.svelte
src/lib/stores/sidebar.ts
src/routes/(console)/project-[region]-[project]/databases/database-[database]/+layout.svelte

update: disable animations on db sheets page.
Reimplements https://github.com/appwrite/console/pull/2258 without regression of overflow issues on body tag.

Fix: sidebar sync state correctly this time.

---

src/lib/components/labelCard.svelte
src/lib/components/organizationUsageLimits.svelte
src/lib/sdk/billing.ts
src/routes/(console)/organization-[organization]/billing/planSummary.svelte
src/routes/(console)/organization-[organization]/change-plan/+page.svelte
src/routes/(console)/organization-[organization]/change-plan/+page.ts

add usage limits component with project selection for Free plan downgrades
yes

Feat:  add usage limits component with project selection for Free plan downgrades

---

src/lib/layout/notifications.svelte

Improves the notification transition, animation.
Manual.
https://github.com/user-attachments/assets/0f6b9956-46f5-4165-a3eb-f66bb225c4ac
N/A.
Yes.

Fix: barebones animation to a nicer one for notifications.

---

src/routes/(console)/project-[region]-[project]/databases/database-[database]/table-[table]/+page.svelte

Update: tooltip message
